### ISSUE TITLE
Delete grid refinement generation utility

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1034]
```[tasklist]
### Tasks
- [ ] tests.integration.test_grid_factory.py
- [ ] grids.refinement, ONLY classes GridSequenceIterator and GridSequenceFactory
```

**Comment by keileg** [comment]
Should have no dependencies

**Comment by IvarStefansson** [comment]
Surely there's something missing on the task list.

**Comment by keileg** [comment]
Sorry, should be updated now.

**Comment by IvarStefansson** [comment]
It has a dependency, namely use of remesh_1d in test_single_phase_flow.py. Suggestions? I suspect we might have similar/relevant functionality elsewhere.

**Comment by IvarStefansson** [comment]
Aha, sorry. I did not read your task description properly.

**Comment by keileg** [comment]
Let's move match_grids.structured_refinement and mdg_refinement to refinement.py
