### ISSUE TITLE
Delete assembler-related methods from discretization classes

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1038]
```[tasklist]
### Methods assemble\_matrix\_rhs, assemble\_matrix, assemble\_rhs in the following classes
- [x] mpfa.py
- [x] tpfa.py
- [x] upwind.py
- [x] mpsa.py
- [x] biot.py
- [x] mass_matrix.py
- [x] fv_elliptic.py
```

```[tasklist]
### Methods assemble_int_bound_flux, assemble_int_bound_source etc.
```

**Comment by IvarStefansson** [comment]
These methods are implicit documentation on how to assemble quantities using the discretization matrices. Should we collect that information? If so, where?

**Comment by keileg** [comment]
This is probably a good point. I just realized that when we just want to assemble a problem, say for testing purposes, this will become a pain, so we should at least keep a recipe. A tutorial sounds wrong, but then where?

I am tempted to add an assembly method in test_utils, or else we need to introduce the same 10 lines of code in multiple places. What do you think?

**Comment by IvarStefansson** [comment]
Let's discuss in person.

**Comment by keileg** [comment]
Please also consider methods `extract_flux`, `extract_pressure` in `fv_elliptic`, and similar methods in `mpsa.py` and `biot.py`
