### ISSUE TITLE
Delete AD versions of GradP, DivU and Stabilization discretization

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#1050]
```[tasklist]
### Tasks
```

**Comment by IvarStefansson** [comment]
Use BiotAd instead in the few places where the classes are used.

**Comment by keileg** [comment]
Agree.

**Comment by IvarStefansson** [comment]
Turns out this is nontrivial because parsing of discretization matrices stored under different keywords (flow/mechanics). Closing unresolved.
