### ISSUE TITLE
Renaming of `bc_type_` methods and raising errors on old names

### ISSUE THREAD

**Issue by Yuriyzabegaev** [pmgbergen/porepy#1074]
Recently, methods for setting a type of boundary condition have been renamed, e.g. `bc_type_mobrho` and `bc_type_darcy` have evolved to `bc_type_fluid_flux` and `bc_type_darcy_flux` respectively. Currently, these methods are named after the flux they affect. After a discussion with @IvarStefansson and @IngridKJ, it was proposed to review all the names of these methods and rename those that don't follow this convention. One specific candidate for renaming: `bc_type_mechanics` -> `bc_type_stress`, since stress is implemented as the nd generalization of flux.

This change may invalidate the runscripts of users who are not aware of the recent renaming. Therefore, we also propose adding all `bc_type_` methods with the old names, such as `bc_type_mobrho`, to the boundary condition mixins. These methods will raise errors that will inform users how to migrate.

**Comment by keileg** [comment]
Makes sense to me.
