### ISSUE TITLE
Generalize typing of numbers

### ISSUE THREAD

**Issue by vlipovac** [pmgbergen/porepy#1085]
The goal is to replace the usage of `pp.numbers` with `numbers.Real` using the standard lib `numbers` from Python.
The reason is to increase the coverage of precision types, see example below:

With
`pp.numbers = Union[int, float]`
we get 
![image](https://github.com/pmgbergen/porepy/assets/68282540/1d9e2d6f-d83b-4d88-87b9-70902f502a05)

**Comment by OmarDuran** [comment]
Thanks @vlipovac. Since this issue doesn't deal with anything essential, I'm closing it for now.
