### ISSUE TITLE
Bug in AdTpfaFlux

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1104]
There seems to be a bug in the AdTpfaFlux mixin class related to Neumann conditions on internal domains.

A likely partial cause is that, in `AdTpfaFlux.diffusive_flux`, filtering on Neumann conditions is only done on external boundaries (contrast this with `AdTpfaFlux.pressure_trace`, where internal boundaries is also filtered). It could also be that both methods need filtering on fracture tips, it seems likely this is currently not done.

To get this right, and properly tested, we need to solve a flow problem with both intersections and fracture tips.

@IvarStefansson: Feel free to add to the problem description.

**Comment by IvarStefansson** [comment]
Agree with the description. This setup might be relevant: https://github.com/pmgbergen/porepy/blob/e4d484f915cde39cc17639e24c1ffe5ab37c1f99/tests/models/test_thermoporomechanics.py#L325
If you use it, could you be bothered to fix https://github.com/pmgbergen/porepy/issues/1108?

**Comment by IvarStefansson** [comment]
Or this one, depending on whether you want to include Fourier or not: https://github.com/pmgbergen/porepy/blob/e4d484f915cde39cc17639e24c1ffe5ab37c1f99/tests/models/test_poromechanics.py#L513

**Comment by keileg** [comment]
> Or this one, depending on whether you want to include Fourier or not:
> 
> https://github.com/pmgbergen/porepy/blob/e4d484f915cde39cc17639e24c1ffe5ab37c1f99/tests/models/test_poromechanics.py#L513

Will do.
