### ISSUE TITLE
Reduction of computational cost in tests

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1122]
We should aim to reduce the time it takes to run the full test suite, without sacrificing test coverage. This can entail testing fewer parameter combinations in parametrized tests and/or reducing the cost of individual tests by considering smaller grids, fewer time steps etc. Skipping of more tests is also an option.

The initial approach will be to identify those with the heaviest cost and see what can be done.

**Comment by OmarDuran** [comment]
Closed related to #1119.

**Comment by IvarStefansson** [comment]
I don't agree this is covered by #1119, which is specifically about tutorial tests.
