### ISSUE TITLE
Darcy and transport

### ISSUE THREAD

**Issue by alessiofumagalli** [pmgbergen/porepy#113]
I'm preparing a jupyter notebook to solve a darcy and transport in a dfm setting. Trying to be as user friendly as possible.

**Comment by keileg** [comment]
@alessiofumagalli  What is the status? Can we close, and if so, can you please post the path to the notebook for future reference?

**Comment by alessiofumagalli** [comment]
It's still in process, once we have a stable version that external people can use without troubles, it will be the time to close it..

**Comment by IvarStefansson** [comment]
Does the new transport tutorial solve this issue?

**Comment by IvarStefansson** [comment]
@alessiofumagalli

**Comment by keileg** [comment]
Can we close?

**Comment by alessiofumagalli** [comment]
no need to have this alive
