### ISSUE TITLE
Problems with installing pymetis in devcontainer

### ISSUE THREAD

**Issue by IngridKJ** [pmgbergen/porepy#1153]
After some update to the porepy image (I do not know exactly which, I just know this used to work before), there are issues with installing pymetis which is needed for bigger simulations. The problem can be recreated by simply trying to install pymetis (pip install pymetis) within a devcontainer running a "new" porepy image. I experienced issues both on the most recent image and on an image that was updated 1-2 weeks ago.

The problem was solved by installing the c++ compiler, g++ (apt install build-essential).

Acknowledgements: Thank you Yura for helping me with troubleshooting what needed to be installed to be able to get pymetis.

**Comment by keileg** [comment]
This sounds like a change in the upstream docker image. Anyhow, it sounds like the solution is to include build-essentials in the apt-get install, https://github.com/pmgbergen/porepy/blob/bfd101eae086be1cd50bbdb28e5ed78adcc7b7cf/dockerfiles/base/Dockerfile#L28
