### ISSUE TITLE
change is_embedded=False to is_embedded=True

### ISSUE THREAD

**Issue by alessiofumagalli** [pmgbergen/porepy#117]
What do you think? We basically use only embedded grids now and keeping track of it can be annoying. Also the True option is always correct (maybe takes a bit more time) the other no.

**Comment by rbe051** [comment]
I don't have any objections

**Comment by keileg** [comment]
Makes sense to me

**Comment by IvarStefansson** [comment]
Sure!

**Comment by keileg** [comment]
Updates here?

**Comment by alessiofumagalli** [comment]
It will be solved once the mortar branch will be merged into develop

**Comment by keileg** [comment]
Fixed by #136
