### ISSUE TITLE
Test Robin approximating Dirichlet

### ISSUE THREAD

**Issue by IngridKJ** [pmgbergen/porepy#1206]
Robin conditions written on the form $\sigma \cdot n + \alpha \cdot u = G$ is supposed to approximate Dirichlet conditions when $\alpha\rightarrow\infty$. This issue addresses writing up a proper test testing this functionality, both for homogeneous and non-homogeneous boundary values. A similar test testing that $\alpha=0$ approximates Neumann is in place after #1187 is merged.

**Comment by jwboth** [comment]
Task: Writing a test for Dirichlet BC via Robin BC, both for homogeneous and non-homogeneous boundary values - Ingrid knows the details. Ingrid has the task of getting Peter to understand Robin BC, and Peter gets the main responsibility to check understandability. 

Outcome: Enhanced test suite for existing capabilities.
