### ISSUE TITLE
Use separate parameter dictionaries for model and numerics setup

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#1210]
Right now, standard practice is not to split parameters into physical and numerical (solver-related) ones, we typically do:
```python
params = {'model_param_1': 'foo', 'solver_param': 'newton'}
model = FooModel(params)
pp.run_time_dependent_model(model, params)
```
This soon leads to a cluttered parameter dictionary and is doomed to introduce inconveniences in naming etc. down the road. A better approach would be to split the two, 
```python
model_params = {'model_param_1': 'foo'}
solver_params = {'solver_param': 'newton'}
model = FooModel(model_params)
pp.run_time_dependent_model(model, solver_params)
```
It is not clear if this is possible at the moment, or if we have made assumptions that means we cannot do such a splitting. This should be investigated. A splitting will require that we define a boundary between the two, which may not always be possible; again we need to understand which problems this may trigger before moving in this direction.

**Comment by jwboth** [comment]
Related to #1150

**Comment by jwboth** [comment]
Task: Answer the question: “Is it possible to make a clean split of the parameter dictionaries into model and solver parameters?” The answer most likely is “yes”, having a look at the parameters used in the solver. If so, update the tutorials and tests using split parameter dictionaries. Recommended: Use your daily simulations for a proper investigation. 

Main outcome: Knowledge about ability to split the parameter dictionaries into two disjointed sets. Infrastructure for model initialization and solution strategy to use different types of parameter dictionaries. Updated tutorials and tests.

**Comment by isakhammer** [comment]
The prepare_simulation boolean parameter holds a high level of importance within the parameter hierarchy, as it not only initializes solver parameters but also configures materials, which are highly model-dependent. A possible improvement could be to decouple the `set_materials `function from the solution strategy, allowing for a clearer separation.



![image](https://github.com/user-attachments/assets/96893d0e-44f1-4e3a-b34f-7b01402e78b4)

**Comment by mikeljordan** [comment]
![Screenshot 2024-08-15 at 14 07 19](https://github.com/user-attachments/assets/24a7eccd-baae-43ac-b7e8-4e40e02e2e15)
Quick glance at some of the params in both solver and physical model, this splitting works by testing with compositional model settings. However, we should also consider to have time_manager as part of solver_params. This should not be too hard to decouple from the physical model params.

**Comment by mikeljordan** [comment]
Branch containing fixes to this issue is `fix-issue-#1210`.

**Comment by jwboth** [comment]
Thank you, Micheal. I suggest, you continue for now. And once, you feel you either get close to finish or willing to share a WIP status of the code, just make a PR. This will make it easier to comment directly to the code changes.

**Comment by isakhammer** [comment]
![image](https://github.com/user-attachments/assets/a4031bb5-88ee-434e-9cc1-434799e055b3)


Any strong opinions on changing `params` to `solver_params`? While it may require some minor renaming throughout the codebase, I believe it aligns better with the goal of this issue.

**Comment by keileg** [comment]
> Any strong opinions on renaming`params` to `solver_params`? While it may require some minor renaming throughout the codebase, I believe it aligns better with the goal of this issue.

Makes sense to me. @IvarStefansson @jwboth what do you think?

**Comment by IvarStefansson** [comment]
I agree, as long as it is only used for solvers.

**Comment by jwboth** [comment]
I also support the suggestion. The way I understood, this issue will be tackled, the `solver_params` will be truely contain only solver parameters. So, regarding Ivar's fear can be silenced.
