### ISSUE TITLE
Placement of the iteration counter in the Newton solver

### ISSUE THREAD

**Issue by mariusnevland** [pmgbergen/porepy#1219]
At the moment, when performing Newton iterations, the iteration counter is updated after the convergence check. This leads to the final iteration not being counted, as you exit the Newton loop before the counter is updated.

Is there a specific reason for the iteration counter being after the convergence check? If not, I would suggest to have the counter before the check.

**Comment by mariusnevland** [comment]
On second thought, I suppose the iteration_counter variable is now redundant, since this is now handled by SolverStatistics (which updates the iteration counter before the convergence check). Hence, we should probably remove iteration_counter and replace its usage everywhere by the num_iteration attribute of SolverStatistics.

**Comment by Yuriyzabegaev** [comment]
#1200 may be related.

**Comment by jwboth** [comment]
Tasks: Consider essentially the second comment by @mariusnevland. `NewtonSolver` should not keep track of iteration counts anymore. Instead, the nonlinear solution statistics object should be consulted. Thus, the task is to clean up the NewtonSolver.

Please also have a look at how the iteration counter is forwarded to `after_nonlinear_convergence`. My intuitive thought is that the explicit forwarding can be removed and again replaced by explicit reference to the `nonlinear_solution_strategy` .
