### ISSUE TITLE
Enum instead of Literal

### ISSUE THREAD

**Issue by jwboth** [pmgbergen/porepy#1220]
Suggestion is to use more Enum type classes instead of using Literals or strings as input arguments for methods. This would allow for better aid of IDEs. 

- One example is the use of `grid_type: Literal["simplex", "cartesian", "tensor_grid"]`. It appears in several (not too many) places in the code. Replacement is easy.
- Another example is the different options for line search (global, local, constraint). Again, an Enum class would give some aid in navigating the options.
- There may be more examples.

**Comment by keileg** [comment]
I see the point. On the other hand, will this not require the user of a function to deal with an enum instead of just writing a string?

**Comment by jwboth** [comment]
Sure. In my view, the main usage is that the user does not need to remember all possible values, and its use is more safe, (if the implementation does not raise ValueErrors). Indeed, it is not crucial. It was just a suggestion.

**Comment by keileg** [comment]
It is an interesting point, the number of options can be bewildering. Perhaps we should discuss at a developer meeting.
