### ISSUE TITLE
Unifying the fluid concept

### ISSUE THREAD

**Issue by vlipovac** [pmgbergen/porepy#1240]
With the introduction of `porepy.compositional`, PorePy allows the user to model general multi-component, multi-phase fluid mixtures, including singular cases of 1-component and/or 1-phase.
The fluid in the PorePy models so far is based on a dict-like data structure for implementing heuristic laws, without the notion of phases and components though. Since this case can be viewed as the 1-phase, 1-component fluid (mixture), unifying the concept of fluids and the respective API for PorePy-models would reduce duplicate code and make PorePy easier to learn by providing only one instead of two concepts.

### Current state

PorePy has the concept of `FluidConstants` included in the modelling framework, upon which various constitutive-law-classes are built to provide domain-based methods like `fluid_density: list[Grid] -> pp.ad.Operator`. The starting point is a model attribute `fluid: FluidConstants`, which is mixed into the model by the solution strategy.

#1186 introduced the compositional sub-package, as a preparation for a general compositional flow model coming in #1236 .
CF models have (as of now) an attribute `fluid_mixture: FluidMixture`, which is provided by a separate, mixed-in class, and which bundles relevant terms in the form of e.g., `model.fluid_mixture.density: list[Grid] -> pp.ad.Operator`.

The consequence of this is that the implementations of balance equations for the CF setting, and the existing fluid mass and energy balance, require to large degree duplicate implementations.

### Proposed change

Since the implementation of fluid-related term can be seen as a family of constitutive laws, it is natural to introduce a more general object as a model attribute, which represents the respective aspect of the model implementation-wise (like `model.mdg` provides in essence every grid-related functionality).

More precisely, an extension of the `model.fluid: FluidConstants` to `model.fluid: FluidMixture` and changing the access of fluid-related terms to use this attribute, i.e.,  `model.fluid.density: list[pp.Grid] -> pp.ad.Operator`.

- It obtains an own place in the model set-up (like the creation of the grid).
- It concentrates the jungle of mixed-in methods `model.fluid_*` in the `model.fluid`, and provides a clear interface, **independent of the phase and component configuration.**
- It takes a chunk out of `constitutive_laws.py` and eases the mixin framework and the coming protocols.
- Balance and other equations (like equilibrium) can be unified to handle an arbitrary fluid mixture.

The name `FluidMixture` should probably changed to `Fluid` for simplicity.

### Challenges

1. While the CF setting is more general, simpler heuristics and singular cases are more frequently used in 
mathematics-oriented research. There is a risk of "bloating" the implementation. For example, the density is in general $\sum_j s_j \rho_j$, which reduces in the 1-phase case to $\rho_0$. While we would like to inform the model that it indeed has a (by the user accessible) phase object in the fluid, the unnecessary expansion of the operator tree of `model.fluid.density` is a legitimate concern. This is relevant for every thermodynamic property. If you think that this is only a minor impact, I would appreciate some feedback since it would make this fix easier.

2. The `Phase` class calls for an EoS-oriented implementation, which also includes the usage of the `SurrogateOperator` and storage of 
   computed property values and derivative values in the memory. Since simpler heuristics do not require any of that and PorePy's AD 
   framework is fully capable to handle it, the full machinery as presented in #1236 is not required.

### Solution

The first step is to unify the class `FluidConstants` and the new class `porepy.compositional.ChemicalSpecies`. A result would be a data-class, with functionality handling unit conversion. The stored data includes:

- Identification/naming: a "name" or formula (f.e. `'H2O'), CASs registry number (international dictionary uniquely identifying any molecule, used by all chemistry-based libraries), ...
- thermodynamic constants: critical p/T, acentric factor, ...
- heuristic constants: compressibility, reference p/T/rho

A modification of the `Component` follows in order to handle this new class.

The second step is to adapt the class `FluidMixture`/`Fluid` as the general model attribute `model.fluid`, which already implements the notion of components and phases, and has extensive logic regarding the DOFs for any number of phases and components.

Third, to modify the model set-up in `prepare_simulation` to include a fluid set-up. Note that the creation of DOFS `create_variables` is already implemented and there is an existing mixin for arbitrary mixtures `CompositionalVariables`. It handles the singular cases without introducing redundant variables.

The final step is incorporate various classes in `constitutive_laws.py` and their concepts in the fluid, and this is the point where design becomes challenging.

1. We can either be mathematically and thermodynamically rigorous and implement "heuristic" phase classes, which represent the existing constitutive laws. To avoid the "bloating" of the equations, the `Fluid` class must be modified to handle the singular cases. The fluid is always clearly defined in terms of phases, components and carries in the singular cases some meta-data with it (like the definition of the physical state of the phase - liquid/gas) and leaves flexibility for future development.

2. We can define derived fluid classes which implement the singular case. It would be a "lightweight" version of the full formulation, but the tradeoff is more code/less unification.

In both cases, the existing solution strategies are fine to handle whatever `fluid` brings with it. But usage of EoS-based phases with external computations and `SurrogateOperator`s as phase properties requires an own solution strategy (see for example [composite-flow/compositional_flow.SolutionStrategyCF](https://github.com/pmgbergen/porepy/blob/7e886cef6e1782ed247aea3ec8d1c1716229ab21/src/porepy/models/compositional_flow.py#L2547)).

### Notes

1. The notion of mobility exists currently in the simple form in [develop/constitutive_laws.FluidMobility](https://github.com/pmgbergen/porepy/blob/7bed70b1159addc58fa7d22f61a2108f7bf1d68f/src/porepy/models/constitutive_laws.py#L729), and in the general form in [composite-flow/ compositional_flow.MobilityCF ](https://github.com/pmgbergen/porepy/blob/7e886cef6e1782ed247aea3ec8d1c1716229ab21/src/porepy/models/compositional_flow.py#L87). It is clear that this must remain a separate mixin implementing the mobility terms which access the `model.fluid`. This is strictly speaking neither a constitutive law, nor a fluid property, but related to the balance equations. It can be unified into a single mixin class though.
4. We will probably require a separate, more general solution for mD-specific terms like normal thermal conductivity.
It exists as a constant given in `FluidConstants` in [develop/constitutive_laws.ThermalConductivityLTE](https://github.com/pmgbergen/porepy/blob/7bed70b1159addc58fa7d22f61a2108f7bf1d68f/src/porepy/models/constitutive_laws.py#L2557), and as a projection of the regular fluid thm. conductivity from the higher-dimensional domain in [composite-flow/compositional_flow.ThermalConductivityCF](https://github.com/pmgbergen/porepy/blob/7bed70b1159addc58fa7d22f61a2108f7bf1d68f/src/porepy/models/constitutive_laws.py#L2557). This is indeed a constitutive law in its sense and will probably remain in two separate classes.
3. There are currently indeed many mixed-in model methods of form `.fluid_*` from various classes in `constitutive_laws.py`. There is room to simplify some implementation along the way since there are several methods which represent only 1 step in the construction of "higher" properties (f.e., `fluid_compressibility` is only used inside a heuristic for `fluid_density`).

### EDIT

Regarding the point about including ""heuristic" phases to accommodate existing heuristic laws in `constitutive_laws.py`, I just realized that `compostional.compositional_mixins.FluidMixtureMixin` provides hooks to define the thermodynamic properties of a phase. These hooks can be used to provide the existing constitutive laws like `DensityFromPressure`, or even better, to modify the `DensityFromPressure` to overwrite the hook via mixing. So I think this would be a great solution which is less invasive in the existing code.

**Comment by keileg** [comment]
@IvarStefansson We should have a look at this quite soon; rapid feedback would be of great aid for @vlipovac in further work

**Comment by keileg** [comment]
Thanks for the, as always, comprehensive information. Immediate questions after a first read:
* The 'singular cases' mentioned in the third step is when there is either a single component or a single phase?
* Is it possible to introduce a special chemical species, 'unit_component' or similar, that serves as a mathematician's representation of a unit fluid - whatever that means?
* Challenge 2, phase class requiring an EOS etc. Do I read correctly that this can be handled under the hood?
* Generalizing the 'fluid' material constant would break the close parallel to the solid material. I think that is fine, but it should be explicitly mentioned. It could be, though, that we should think about whether to relocate the unit conversion machinery to somewhere less tied to the physics.
* The fourth step, reimplementation of constitutive laws, I think I will need a discussion to fully understand. I suggest we coordinate with @IvarStefansson.
* The final comment to the fourth step, about the need for additional work in the solution strategy if we an EOS-based approach: Is it a correct interpretation that (unless we do something clever with mixins or similar), if we allow for both EOS and simple approach and decide to simulate, say, a poromechanical system with a 'mathematical' and real fluid, this would require changes to both the fluid and the solution strategy?
* Your EDIT is arguing in favor of using an EOS-based representation also of the mathematician's fluid?

**Comment by vlipovac** [comment]
To answer @keileg 

1. Yes, singular cases refer to either 1 phase, or 1 component, or both.
2. This unit component can be introduced as a base for the more complex Species, yes.
3. Yes it can be handled under the hood, similar to introducing a unit species, a unit EoS can be introduced, and invisible to the user in the regular use cases.
4. In my opinion, the generalization for the solid will come anyways as well, as soon as chemistry or non-constant permeabilities are tackled. My hunch is that the solid will also be represented by some chemical species (or mixture) in the future.
5. This is related to the EDIT, there is a solution without major re-implementation, but with changing the names of some of the present methods to override f.e. [this method](https://github.com/pmgbergen/porepy/blob/7bed70b1159addc58fa7d22f61a2108f7bf1d68f/src/porepy/compositional/compositional_mixins.py#L1306) via mixin.
6. and 7. No changes to existing solution strategies with the introduction of a mathematicians EoS as mention in 3. The mathematician's EoS would be there for completeness to align the CF and current model. But a new solution strategy is required when a real EoS is used, since terms in the equations represented by `SurrogateFactory` require a separate update step before, say, re-discretizing. To get an idea, see [SolutionStrategyCF](https://github.com/pmgbergen/porepy/blob/7e886cef6e1782ed247aea3ec8d1c1716229ab21/src/porepy/models/compositional_flow.py#L2547). I think this is easier to explain in person perhaps.
