### ISSUE TITLE
Isolation of Units and conversion functionality

### ISSUE THREAD

**Issue by jwboth** [pmgbergen/porepy#1247]
As identified in #1244, an isolation of the units concept would allow for persistent use instead of attaching it both to fluids and solid etc. This is thus requested independent of the discussion in #1244. 

The process shall be performed through a user project with the two tasks of 1. removing the functionality from MaterialConstants and moving to a separate Units location, and 2. updating the code base accordingly.

These changes are important for the user project #1150 on numerical constants.

**Comment by vlipovac** [comment]
Is it okay to resolve this issue together with #1244 ?
For practical reasons of diverging code basis.

**Comment by jwboth** [comment]
Naively, I was hoping that this issue was sufficiently isolated from develop, and your changes so far (but wrongfully, I did not check the current state of your PR). For me, this sounds OK, especially taking into account your availability after next week. Please organize your time as efficiently as you can.

**Comment by vlipovac** [comment]
I know it's bad practice, but this one time it will help reduce the amount of refactoring, thanks!

**Comment by keileg** [comment]
Makes sense to me.
