### ISSUE TITLE
Issue when exporting initial condition (time_step=0)

### ISSUE THREAD

**Issue by rbe051** [pmgbergen/porepy#128]
this does not work:

```python
import numpy as np
import porepy as pp

gb = pp.meshing.cart_grid([], [10, 10, 10])
(Pdb) exp = pp.Exporter(gb, 'temp')
(Pdb) exp.write_vtk(time_step=0)
```

It runs and writes the file, but the .pvd file is wrong. I can however open the .vtk files

**Comment by keileg** [comment]
@rbe051 @alessiofumagalli  What is the status of this one?

**Comment by alessiofumagalli** [comment]
mmm, I don't even remember that we had an issue related to this problem.. @rbe051 ?

**Comment by rbe051** [comment]
I don't remember why I wanted to do this. But I think we fixed it
