### ISSUE TITLE
vem.py run errors

### ISSUE THREAD

**Issue by Bushvek** [pmgbergen/porepy#130]
Hi there, I am new to porepy and trying to run the vem.py in a Ubuntu machine but will receive the following errors for different lines:
**1. import from csv**
`gb = importer.from_csv('network.csv', mesh_kwargs, domain)`

> AttributeError: module 'porepy.fracs.importer' has no attribute 'from_csv'

I changed it to the following line and looks it is working:
`gb = importer.dfm_2d_from_csv('network.csv', mesh_kwargs, domain)`

**2. export the grid block to paraview**
`exporter.export_vtk(gb, 'grid', folder='vem')`

> AttributeError: module 'porepy.viz.exporter' has no attribute 'export_vtk'

I tried different functions such as `_export_vtk_2d`, no success.
after commenting the above exporting line, i receive this error:

>  File "/home/reza/Codes/porepy/examples/example1/benchmark4/vem.py", line 67, in add_data
    gb.add_edge_prop('kn')

> AttributeError: 'GridBucket' object has no attribute 'add_edge_prop'

I appreciate your help on these issues.
Reza

**Comment by keileg** [comment]
Hi,

We changed some function names a while ago, the old names had lost their logic, but forgot to update this script. Thanks for pointing it out.

 @alessiofumagalli , I fixed the dfm import, but got confused in the Exporter. Could you have a look?

**Comment by keileg** [comment]
See branch issue_130

**Comment by alessiofumagalli** [comment]
Dear @Bushvek, welcome!
Can you please give as a minimal example? Or tell us which file (and branch) are you using?
thanks a lot

**Comment by Bushvek** [comment]
Dear @alessiofumagalli,

Attached are the main vem.py file as well as the modified version (i.e. I changed some of the function names accordingly). I tried to add a comment with capital letter in front of the old commands.

[VEM.tar.gz](https://github.com/pmgbergen/porepy/files/1974395/VEM.tar.gz)

**Comment by alessiofumagalli** [comment]
thanks
I'm assuming you are using the develop branch

**Comment by alessiofumagalli** [comment]
try to use the attached file.. it should work. we did a big clean up of the code and some of the example were not updated.

[example.py.zip](https://github.com/pmgbergen/porepy/files/1974438/example.py.zip)

**Comment by Bushvek** [comment]
Yes, I am using the develop branch. I am sorry but the code you sent me also does not run and gives me _AssertionError_ as below:

`runfile('/home/reza/Desktop/RUN/Example/example.py', wdir='/home/reza/Desktop/RUN/Example')
Reloaded modules: porepy_config
Traceback (most recent call last):

  File "<ipython-input-62-0f78d379e99d>", line 1, in <module>
    runfile('/home/reza/Desktop/RUN/Example/example.py', wdir='/home/reza/Desktop/RUN/Example')

  File "/home/reza/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/reza/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/reza/Desktop/RUN/Example/example.py", line 98, in <module>
    main()

  File "/home/reza/Desktop/RUN/Example/example.py", line 74, in main
    gb, domain = pp.importer.dfm_2d_from_csv(network, mesh_kwargs, return_domain=True)

  File "/home/reza/anaconda3/lib/python3.6/site-packages/porepy/fracs/importer.py", line 217, in dfm_2d_from_csv
    return meshing.simplex_grid(f_set, domain, **mesh_kwargs), domain

  File "/home/reza/anaconda3/lib/python3.6/site-packages/porepy/fracs/meshing.py", line 119, in simplex_grid
    grids = simplex.triangle_grid(frac_dic, domain, **kwargs)

  File "/home/reza/anaconda3/lib/python3.6/site-packages/porepy/fracs/simplex.py", line 427, in triangle_grid
    return triangle_grid_from_gmsh(file_name, **kwargs)

  File "/home/reza/anaconda3/lib/python3.6/site-packages/porepy/fracs/simplex.py", line 483, in triangle_grid_from_gmsh
    pts, cells, phys_names, cell_info, line_tag=const.PHYSICAL_NAME_FRACTURES)

  File "/home/reza/anaconda3/lib/python3.6/site-packages/porepy/grids/gmsh/mesh_2_grid.py", line 176, in create_1d_grids
    g = create_embedded_line_grid(loc_coord, loc_pts_1d)

  File "/home/reza/anaconda3/lib/python3.6/site-packages/porepy/grids/gmsh/mesh_2_grid.py", line 206, in create_embedded_line_grid
    assert cg.is_collinear(loc_coord, atol)

AssertionError`

Also a quick question. Do you have any example available concerning the hydraulic shearing of fractures? I could not find in any examples.

**Comment by alessiofumagalli** [comment]
co-linearity is always a very nasty problem, especially for real networks.. if your fracture are planar up to a tolerance you can tune this. otherwise just run the code with the -O option to disable the assertions.

**Comment by alessiofumagalli** [comment]
about the hydraulic shearing, I forward your question to @rbe051  and @keileg

**Comment by Bushvek** [comment]
Thanks @alessiofumagalli. It is working now properly. Thanks also for forwarding my question.

**Comment by alessiofumagalli** [comment]
don't esitate to ask further questions :)

**Comment by keileg** [comment]
@alessiofumagalli : Can you push the code to develop and close the issue?
