### ISSUE TITLE
Bug in refinement.refine_grid_1d()

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#135]
The following code fails:

g = pp.TensorGrid(np.array([0, 1, 2, 3]))
h = refinement.refine_grid_1d(g)

The cell-face relation seems to be indexed with the wrong size. If I make g a grid with two cells instead of 3, everything is fine.

I just added a lot of comments to the code, commit 7471bd, but have changed no functionality.

**Comment by alessiofumagalli** [comment]
is it still an issue?

**Comment by keileg** [comment]
I think this should be resolved now - we will reopen if problems reemerge.
