### ISSUE TITLE
Convergence tests for mpsa not running

### ISSUE THREAD

**Issue by rbe051** [pmgbergen/porepy#146]
The convergence tests for mpsa does not run. It is converging, but it gives different results from the hard coded values (added 12.06.2017). Is there any changes in mpsa where we should expect the solution to differ?

**Comment by keileg** [comment]
We did some changes to inhomogeneous Neumann conditions some months ago. Is this the case you consider?

**Comment by rbe051** [comment]
yes. I should have said I was running the convergence tests in Example 2

**Comment by rbe051** [comment]
I saw there was a comment about non-optimal convergence rates (1 for displacement and 0.5 for stress) when applying Neumann conditions. This has not improved

**Comment by mstarnoni** [comment]
Yes, there is a non-optimal convergence rate when applying non-zero Neumann BC. But I believe this was a long-lasting issue. My modifications did not impact standard mpsa.

**Comment by mstarnoni** [comment]
Apparently there is an issue with non-zero neumann. All-dirichlet, and zero-Neumann give desired convergence - order 2 for both displacement and stress. Same applies for mixed dirichlet-zero neumann (through bc_vectorial). Problems arise with non-zero neumann. I believe this was already recognized in earlier mpsa, since what seems to be an ad-hoc method "_zero_neu_rows" was already there, my guess, to mitigate this issue. Note that this latter method does not have a counterpart in mpfa.

**Comment by rbe051** [comment]
So let me just write down something before I forget. If I force eta=0 for triangular grids everything works fine for the Dirichlet boundaries. Still wrong for Neumann

**Comment by keileg** [comment]
Forcing eta=0 should not make a difference; this is automatically done on boundary faces for Dirichlet points (and as Michele noted above, this case works well anyhow). On Neumann faces, there is no continuity condition, thus eta does not matter.

**Comment by rbe051** [comment]
I wrote my last comment in a rush before I had to leave, I'll give some more details:

By setting eta=0, the case for pure Dirichlet boundaries passes the tests for the hard coded values. I guess when the hard coded values was set the code defaulted to eta=0. 

The hard coded values for Neumann still gives a different answer (the test case still have two Dirichlet boundaries that would be affected by eta), but this is probably explained by @mstarnoni changes.

**Comment by keileg** [comment]
I see. You are probably right that the original values were computed with
eta=0 (this most likely was before we implemented the automatic tuning of
eta to the grid type, in fvutils.determine_eta()).

To summarize: The behavior for Dirichlet is okay, but the reference values
should be updated. For Neumann, the values should be updated, but the code
also behaves strangely, so some debugging remains. Does this sound true?

**Comment by rbe051** [comment]
I agree!. I will fix and then close issue

**Comment by keileg** [comment]
Resolved by a7fc23a
