### ISSUE TITLE
Installed on Mac But Code test codes don't work

### ISSUE THREAD

**Issue by femorode** [pmgbergen/porepy#150]
I was able to successfully install porepy on my Mac, but all test codes fail at the point where porepy is imported. That is, on the line: "import porepy as pp".
The error message I got while running testfv.py is given below. Any ideas on how to fix this?

An error ocurred while starting the kernel
Fatal Python error: PyThreadState_Get: no current thread

Thanks

**Comment by keileg** [comment]
As you see from the installation instructions, Mac is uncharted waters for us. We recently ran into some issues with a similar install, these are not yet install. If we get any closer, I will update here.

More constructively: What you describe sounds like an issue with the pythonpath. Did you install from pypi, or by clone and then pip install . (the latter is recommended)? Anyhow, once this is done, and you are in the right virtual environment, simply opening python and running import porepy should work.

**Comment by keileg** [comment]
Update: We get exactly the same error message, but have no idea on how to fix it. It looks like we will use virtual box to get PorePy running on a Mac.

**Comment by keileg** [comment]
I have updated the install instructions for Mac, the recommended solution is now VirtualBox with a Linux image.

I'll close this issue now; feel free to reopen should you have further questions. And sorry for not being more constructive - none of the developers have any experience with Mac, so we basically have no idea on how to approach this.
