### ISSUE TITLE
Unified boundary conditions

### ISSUE THREAD

**Issue by rbe051** [pmgbergen/porepy#155]
Our boundary conditions are a mess. We now have three classes BoundaryCondition, BoundaryConditionVectorial and BoundaryConditionNodes, where the two first at least does more or less the same.

When it comes to the discretizations they show that they were written for BoundaryCondition, even though it might have been more natural to use BoundaryConditionVectorial (mpsa). This have resulted in some hacks to make BoundaryCondition works for vectors, and hacks to un-hack the hacks (!) when BoundaryConditionVectorial was implemented, e.g., see ExludeBoundaries in fvutils.

Ideally we should merge BoundaryCondition and BoundaryConditionVectorial (and maybe BoundaryConditionNodes), and let the discretization decide what kind of BC you should assign (mpsa wants vectors, tpfa scalars, RT0 nodes)

**Comment by keileg** [comment]
I completely agree; our treatment of boundary conditions has mostly been quick fixes to an initial implementation that was limited in scope. My suggestions:

1. We keep vector and scalar BCs, with the intention that MPSA (and other future discretizations of vector problems) will only accept vector conditions. This should simplify the scalar conditions, and make assignment and invocation of BCs more transparent. 

2. I agree, we need a plan for how to treat both nodal and facial BCs. The former is now relevant for FEM / primal VEM, but it may also become relevant for a future FEM for mehcanics - watch this space. My best suggestion is to have only two BC classes (scalar and vector), let the user define both nodal and facial conditions, and leave it to the user / numerical method to make a pick. 

Opinions @rbe051 @alessiofumagalli @mstarnoni @IvarStefansson ?

**Comment by IvarStefansson** [comment]
By "let the user define both nodal and facial conditions", do you mean that the user is free to define both, or has to? In the former case, do unset conditions default to some specific choice (can lead to confusion), or does one have to define them (can become inconvenient/cumbersome)?

**Comment by keileg** [comment]
Summary of discussion between @IvarStefansson  and @keileg: In principle, the user is responsible that the discretization has access to whatever boundary data is necessary.

When it comes to what are default conditions, both type and value, this may be important. The two options are 1) Values are None or similar, so that we get an error message if accessing an unset field. 2) We keep the current practice giving defaults, with the caveat that the opportunities for overlooking something increases with option complexity. 

Suggestions?

**Comment by rbe051** [comment]
I suggest something like this
BoundaryConditionVectorial(g).
assigns everything to False 
BoundaryCondtitionVectorial(g, 'neu')
Assigns everything to Neumann (which is what is default now), and similar for 'dir' and 'rob'

**Comment by keileg** [comment]
@rbe051 : Can we close this one?

**Comment by rbe051** [comment]
I guess so
