### ISSUE TITLE
Tutorial on Darcy and transport fails

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#162]
Nightly run on travis gave error message. It seems to be a key error of the normal permeability of fractures.

**Comment by alessiofumagalli** [comment]
OK, however the main problem is that the jupyter-notebook file darcy_and_transport.ipynb is not really works. The problem is the well approximation for the transport part. What do you suggest? Remove it? Or do only the pressure?

**Comment by keileg** [comment]
It cannot be in the tutorial and not work. If it is only Darcy, does it
still a as something compared to the other tutorials?

**Comment by alessiofumagalli** [comment]
not really, it was this file I tried to prepare for Luisa

**Comment by alessiofumagalli** [comment]
@keileg , is it still an issue?

**Comment by IvarStefansson** [comment]
I think this is one of those I moved away from the tutorials, because we do not use the "models" anymore.
