### ISSUE TITLE
Does porepy support general finite element discretizations?

### ISSUE THREAD

**Issue by fanronghong** [pmgbergen/porepy#165]
As far as I know, porepy doesn't support finite element discretization, only for finite volumes method, right?

**Comment by alessiofumagalli** [comment]
Hi, porepy support RT0, MVEM0, and P1 to discretize flow-like equations

**Comment by keileg** [comment]
We do have an implementation of P1 finite elements for flow, although this is not a good option for problems with fractures, nor for general heterogeneous parameter fields if you care about conservation, which we tend to do. We also have lowest order formulations for mixed finite elements (RT0) and  mixed virtual finite elements, both of which are much better behaved for flow problems.

If you're thinking of a more general framework, in terms of either more equations or different and possibly higher order schemes the answer is no. Moreover, I don't see this being implemented anytime soon either, the only possible exception is P1 for elasticity, but it is far from sure we will enter into this. More general frameworks like fenics are filling this part, and we're really not in that business.

**Comment by fanronghong** [comment]
Thanks @alessiofumagalli and @keileg for your reply.
