### ISSUE TITLE
The computing domain must be a box?

### ISSUE THREAD

**Issue by fanronghong** [pmgbergen/porepy#166]
Hi all,
I find computing domain must be a box, right? Because I see a domain must be defined by (x_min, x_max, y_min, y_max, z_min, z_max).
Can I use a simplex as the computing domain, like tetrahedra? Thanks in advance.

**Comment by keileg** [comment]
The meshing functionality, including treatment of fracture networks, are based on box-type domains. Extensions should not be difficult, but probably tedious, we have just never had the need for this.

If you somehow make the mesh, the rest of the code should mainly be agnostic to the shape of the domain. The only exception that I can think of right now is some utility functions for identification of faces on specific parts of the boundary; I can't promise there are no other special cases, though. So, if you can define your mesh externally to PorePy, for instance by gmsh accessed by pygmsh or similar, this should work fine. The case where this approach fails will typically be if the geometry is complex, say you have many fractures crossing: Then you need to split the fractures before meshing, and doing this yourself is no fun. 

Did that make sense?

**Comment by fanronghong** [comment]
Thanks @keileg.

**Comment by keileg** [comment]
As a follow-up, we have just added code that allows for general domains (also non-convex). The boundary is specified by a set of bounding polygons that together form a polyhedron.

The code is somewhat unpolished at the moment, but if you stick with convex geometries, it should behave as expected.
