### ISSUE TITLE
Python 3.5 Travis failure

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#177]
In Python 3.5, the tutorial on dfn meshing fails:

`/porepy/fracs/split_grid.py", line 242, in duplicate_faces
    update_values[i] = gh.tags[key][frac_id]
IndexError: index 256 is out of bounds for axis 0 with size 256`

Moreover, the unit test test_tag_gmsh.py fails randomly in 3.5, and the tests take longer than usual on Python 3.6.

**Comment by keileg** [comment]
@alessiofumagalli : From what I can see, you made the code and the test. Would you care to have a look?

**Comment by IvarStefansson** [comment]
Note that the tutorial only seems to fail on the cron runs.

**Comment by alessiofumagalli** [comment]
@IvarStefansson , should we close this issue?
