### ISSUE TITLE
Edge assembly error

### ISSUE THREAD

**Issue by rbe051** [pmgbergen/porepy#179]
The assembler can not assemble edge-discretization when multiple node-variables are present.

The problem is that it is trying to access a dictionary key that is not present.

See example below

```python
import numpy as np
import porepy as pp

f = np.array([[1, 1], [2, 1]]).T
gb = pp.meshing.cart_grid([f], [3, 3])

for g, d in gb:
    d[pp.PRIMARY_VARIABLES] = {
        'pressure1': {"cells": 1},
        'pressure2': {"cells": 1},
    }
    d[pp.DISCRETIZATION] = {
        'pressure1': {"diffusive": pp.Tpfa('pressure1')},
        'pressure2': {"diffusive": pp.Tpfa('pressure1'),}
    }

    flow_data = pp.params.parameter_dictionaries.flow_dictionary(g)
    pp.initialize_data(d, g, 'pressure1', flow_data)

coupler = pp.RobinCoupling('pressure1', pp.Tpfa('pressure1'))
for e, d in gb.edges():
    mg = d['mortar_grid']
    g1, g2 = gb.nodes_of_edge(e)
    d[pp.PRIMARY_VARIABLES] = {'pressure1': {"cells": 1}}
    d[pp.COUPLING_DISCRETIZATION] = {
        'lambda': {
            g1: ('pressure1', "diffusive"),
            g2: ('pressure1', "diffusive"),
            e: ('pressure1', coupler),
            },
        'lambda_2': {
            g1: ('pressure2', "diffusive"),
            g2: ('pressure2', "diffusive"),
            e: ('pressure2', coupler),
        }
    }

    pp.initialize_data(d, mg, 'pressure1', {"normal_diffusivity":1})
assembler = pp.Assembler()
assembler.assemble_matrix_rhs(gb)


```

**Comment by rbe051** [comment]
Using your example and only discretizing the first variable we still get a key error: 
```python
assembler.assemble_matrix_rhs(gb, variables=['pressure1'])
```
I was a bit quick in writing the example and defined the wrong primal variables on the edge. I would actually expect something like this:
```python
for e, d in gb.edges():
    mg = d['mortar_grid']
    g1, g2 = gb.nodes_of_edge(e)
    d[pp.PRIMARY_VARIABLES] = {'lambda': {"cells": 1}, 'lambda_2': {"cells": 1}}
```
and not the pressure1 and pressure2 variables that should only live on the nodes.

I think maybe I did another mistake when defining the coupling discretization, but we can take this after the documentation is updated. The key-error when only discretizing one variable is happening anyhow.

**Comment by alessiofumagalli** [comment]
@rbe051 , what's the status?

**Comment by rbe051** [comment]
To my knowledge it is still an issue

**Comment by IvarStefansson** [comment]
I ran into similar problems when defining a subset of active variables. The assembler seems to loop through all edge discretizations, without checking whether they should be active or not.

**Comment by keileg** [comment]
I will look into this tomorrow. Likely, the filtering on active variables is not complete, and the corresponding unit test is lacking.

**Comment by keileg** [comment]
I believe #254 fixed this. Please reopen if I am wrong.
