### ISSUE TITLE
Boundary contribution fv_elliptic

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#196]
The rhs contribution from assemble_int_bound_pressure_trace is missing (fractures extending to boundary).

**Comment by keileg** [comment]
Indeed, @rbe051  has pointed this out earlier. I do not think it will be a major fix, but I am a bit unsure about how it fits with the data structures.

**Comment by keileg** [comment]
Can we close this?

**Comment by rbe051** [comment]
no, it is not fixed

**Comment by rbe051** [comment]
soved by pull request #222
