### ISSUE TITLE
unit test test_half_space fails with scipy v>=1.0

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#202]
Two of the unit tests fails when used with scipy 1.0 or higher. My guess is that the change is related to the method utils.half_space_pt, which uses scipy.linprog.

Update: From what I understand of Travis behavior, python 3.7 requires (read: is readily available to travis) scipy > =1.0, while py3.5 needs scipy < 0.19. Thus we need both versions.

**Comment by alessiofumagalli** [comment]
how can I test this? do I need a python 3.7 installation?

**Comment by keileg** [comment]
I think you can reproduce it by updating to scipy 1 in python 3.6.

The reason 3.7 fails is that it needs scipy 1.x.  I have more or less mapped out the necessary modifications to the requirements to be compatible with 3.5-3.7; this is one of the outstanding issues.

**Comment by alessiofumagalli** [comment]
ok, thanks. I'll try now

**Comment by alessiofumagalli** [comment]
With this configuration I don't get any problem
[package.txt](https://github.com/pmgbergen/porepy/files/2807348/package.txt)

**Comment by keileg** [comment]
Can you check out the branch py37, with the package versions as specified in that requirements-dev file? I think it should still fail in python 3.6

**Comment by alessiofumagalli** [comment]
it looks like it work without any problem... what was special about the requirements-dev? can I get the specification of your env?

**Comment by keileg** [comment]
Fixed during update to 3.7. The problem was that the known answer had hard coded too strong assumptions on the ordering of points.
