### ISSUE TITLE
MPSA changes the constitutive equations

### ISSUE THREAD

**Issue by 92runarlb** [pmgbergen/porepy#21]
Minimal example:

`
import numpy as np

from porepy.grids import structured
from porepy.params import fourth_order_tensor, bc
from porepy.numerics.fv import mpsa

n = 5
g = structured.CartGrid([n,n])
g.compute_geometry()

dirich = np.ravel(np.argwhere(g.face_centers[1] < 1e-10))
bound = bc.BoundaryCondition(g, dirich, ['dir']*dirich.size)

lam = np.ones(g.num_cells)
mu = np.ones(g.num_cells)
constit = fourth_order_tensor.FourthOrderTensor(g.dim, mu, lam)

_, _ = mpsa.mpsa(g, constit, bound)

_, _ = mpsa.mpsa(g, constit, bound)
`

**Comment by keileg** [comment]
I'll take care of this, I know where to look.
