### ISSUE TITLE
Transient problems support

### ISSUE THREAD

**Issue by AbsoluteStratos** [pmgbergen/porepy#213]
Hi,

I was curious if PorePy has transient support or is entirely a steady-state solver at the moment. I did notice there is an example is a transport however it appears this is steady-state. Would it be possible to used PorePy for transient problems if you discretize the time time derivative with finite-difference then iteratively used PorePy to solve the system at each time-step similar to if you were using FEM in FEniCS? Any potential for a transient scalar transport, such as contaminates flowing though an underground porous media?

If there are some transient examples, please point me to them as I must of missed them.
Many Thanks!
Nick

**Comment by keileg** [comment]
Hi, and thanks for you interest.

The solution you sketch is indeed our philosophy: The building blocks are there for transient problems (both advection, diffusion and a combination), but for the moment you will need to set up the time stepping scheme yourself; this should be fairly straightforward if you stick with simple schemes. 

@IvarStefansson  : You probably know better than me where to look for suitable examples, can you please fill in?

**Comment by keileg** [comment]
Update: @IvarStefansson went ahead and made a tutorial that covers solving a Darcy problem, and then do linear transport on the flux field; see tutorials/tracer_transport. It should show you how to couple together the ingredients.

**Comment by AbsoluteStratos** [comment]
Awesome, thank you so much for the very quick response. I will give this tutorial a read, I really appreciate it.
