### ISSUE TITLE
Signs in MPFA

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#239]
MPFA, and to a lesser degree MPSA and fv_elliptic, have several seemingly random or poorly explained sign changes. Some are related to the direction of face normal vectors. A structured cleaning up would be beneficial.

**Comment by keileg** [comment]
@IvarStefansson : I think we have done what we can for now here, with the merge of #249 
We really ought to re-implement the whole finite volume package, but short of that, the code will stay as it is. That is: Can we close?

**Comment by rbe051** [comment]
I belive so
