### ISSUE TITLE
Missing "compressible_flow_with_automatic_differentiation" tutorial

### ISSUE THREAD

**Issue by femorode** [pmgbergen/porepy#281]
I noticed that the "automatic_differentiation.ipynb" tutorial references the "compressible_flow_with_automatic_differentiation" tutorial, which is appears to be missing in the tutorials or examples folder.

**Comment by keileg** [comment]
@rbe051 : Do you know the status of this one?

**Comment by rbe051** [comment]
It seems that the tutorial was outdated at some point and moved to examples/examples10. I have revived the tutorial and made a pull request for it. It should be merged back into develop within a day or two.

**Comment by rbe051** [comment]
Fixed by pull request #282
