### ISSUE TITLE
Update docker image on docker hub

### ISSUE THREAD

**Issue by haakon-e** [pmgbergen/porepy#305]
Hi,
I see that the porepy project has been updated lately, while the (experimental) Docker image has not (https://hub.docker.com/r/keileg/porepy).
Could this be updated? I'm currently having trouble building the Docker image from scratch locally.

Best

**Comment by keileg** [comment]
I just pushed an update (based on the latest version of master). Could you verify that it works as expected?

**Comment by haakon-e** [comment]
After thorough investigation, I have found the the 'WHAT' of the problem. The 'WHY' is still a mystery to me.

## Code output for pulled images
On your docker hub page, you have two tagged versions of porepy: `v1.0` and `latest`. I pulled both, with the following result:
```
(base) haakon@haakon-VirtualBox:~$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
keileg/porepy       v1.0                0137ba283161        27 hours ago        4GB
keileg/porepy       latest              ae0cb78423dc        3 months ago        3.89GB
(base) haakon@haakon-VirtualBox:~$ docker run -it keileg/porepy:v1.0
docker: Error response from daemon: linux spec user: unable to find user POREPY: no matching entries in passwd file.
(base) haakon@haakon-VirtualBox:~$ docker run -it keileg/porepy:latest
porepy@242708153fbb:~$ ipython
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:                                                                                                               
Do you really want to exit ([y]/n)? 
porepy@242708153fbb:~$ exit
(base) haakon@haakon-VirtualBox:~$ 
```
### Comments
In other words, when pulling `keileg/porepy` with tag `:latest`, I get the old image. When I use the tag `:v1.0`, I get the new image. However, the new image won't run because: `docker: Error response from daemon: linux spec user: unable to find user POREPY: no matching entries in passwd file.`
Link to related SO answer for context: https://stackoverflow.com/a/53726938
Note that the official "workaround" by docker (see: https://success.docker.com/article/ucp-health-checks-fail-unable-to-find-user-nobody-no-matching-entries-in-passwd-file-observed) does not work, and gives me the following error:
```
(base) haakon@haakon-VirtualBox:~$ sudo systemctl restart docker
Failed to restart docker.service: Unit docker.service not found.
```
I'm not running docker as a service in the background as far as I know, so the proposed work-around won't work for my setup.

For reference, the sha key for the `v1.0` is: `sha256:2b3138f9e99b3ec6de7714ae42baf14d3695d21ff122051e5ba3c00ad2208796`, so you can verify you have the same.

Next, as you can see, the "old" image runs as expected:
## Code output for `:latest` tagged image

Command line interface:
```
(base) haakon@haakon-VirtualBox:~$ docker pull keileg/porepy
Using default tag: latest
latest: Pulling from keileg/porepy
6abc03819f3e: Pull complete 
05731e63f211: Pull complete 
0bd67c50d6be: Pull complete 
bd846601ce7e: Pull complete 
e6445b29f447: Pull complete 
ac7ae8fe6e70: Pull complete 
3abce9a16fa7: Pull complete 
8c5e1ed1f301: Pull complete 
00fb29e84aa7: Pull complete 
47deb9f7dd8c: Pull complete 
096aa2f3885e: Pull complete 
e2f2e4315c06: Pull complete 
34625c2dbb99: Pull complete 
caac1a9159fe: Pull complete 
e56224157ef6: Pull complete 
52a2467ffccd: Pull complete 
76d5b6c22cca: Pull complete 
b4453137b884: Pull complete 
b20da0b1fd5e: Pull complete 
7c7cf232459f: Pull complete 
f8aaf350cde4: Pull complete 
7a2cdfc3656d: Pull complete 
7b10cee20fc9: Pull complete 
e1c848411a4a: Pull complete 
6c1790485fd1: Pull complete 
Digest: sha256:cec70d07b3251bb5e3cdbfae2ec8f9983c519828deb325bca89e21cc101fc78e
Status: Downloaded newer image for keileg/porepy:latest
(base) haakon@haakon-VirtualBox:~$ docker run -it keileg/porepy
porepy@8282c2dd0afd:~$ ipython
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import porepy as pp                                                                                           
/home/porepy/.conda/lib/python3.7/site-packages/porepy-0.5.0-py3.7-linux-x86_64.egg/porepy/fracs/fractures.py:27: UserWarning: VTK module is not available. Export of fracture network to    vtk will not work.
  vtk will not work."
/home/porepy/.conda/lib/python3.7/site-packages/porepy-0.5.0-py3.7-linux-x86_64.egg/porepy/viz/exporter.py:22: UserWarning: No vtk module loaded.
  warnings.warn("No vtk module loaded.")
/home/porepy/.conda/lib/python3.7/site-packages/porepy-0.5.0-py3.7-linux-x86_64.egg/porepy/grids/partition.py:19: UserWarning: Could not import pymetis. Some functions will not work as    intended
  intended"

In [2]: pp.SecondOrderTensor()                                                                                        
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-c110011d0edd> in <module>
----> 1 pp.SecondOrderTensor()

TypeError: __init__() missing 2 required positional arguments: 'dim' and 'kxx'

In [3]:      
```

As you can see, I have actually two problems. Let's start with the bottom one.
I call pp.SecondOrderTensor() without arguments because that is where I first understood I had an old image. You updated SecondOrderTensor (ref: https://github.com/pmgbergen/porepy/commit/fde32d8c6bd613f5b51ea85213a5f3ce610e4aca#diff-c3b3b292a31cea64b3156623753064ef) to no longer accept `dim` as argument when initializing an instance of the class SecondOrderTensor.
Since my image gives me the above error, I have an older version of the docker image. This is also apparent from `docker images` (first code snippet).

Another note is the warning I get when importing `porepy`. It warns that no `vtk` module is loaded. This is an issue I have experienced for some time when running the code (in the regular recommended way) locally too, but have fixed on my end. For some reason, my version of the docker image does not recognise `vtk`. Perhaps this is because I have an older version of the image? 
I will look at that problem again when I get the new version of the Docker image to run.

**Comment by keileg** [comment]
I deleted the image with the 'latest' tag, that should remove the scope for ambiguity.

Please note that the Docker functionality should be seen as a preliminary experiment; for the moment we have limited capacity to develop this further. If you will use PorePy in a project, the clear recommendation is to do a standard install on a Linux system (or Mac, but we also have limited knowledge on how that is working).

**Comment by dbarolirwth** [comment]
@keileg  i will get a look on permission soon and dockerfile.
