### ISSUE TITLE
Add dot to a line in utils > sort_points.py

### ISSUE THREAD

**Issue by haakon-e** [pmgbergen/porepy#307]
Hi,

## Reproducable code
I was trying to create a 3D plot with the following code:
```
g = pp.CartGrid([10,10,10])
g.compute_geometry()
pp.plot_grid(g, info="all", alpha=0.5, figsize=(15,12))
```

## Error message
which resulted in the following error (shortened):
```
~/porepy/src/porepy/utils/sort_points.py in sort_point_plane(pts, centre, normal)
    110 
    111     """
--> 112     R = pp.map_geometryproject_plane_matrix(pts, normal)
    113     pts = np.array([np.dot(R, p) for p in pts.T]).T
    114     centre = np.dot(R, centre)

AttributeError: module 'porepy' has no attribute 'map_geometryproject_plane_matrix'
```

## Proposed solution
It seems like there should be a dot, so that the line becomes:
` R = pp.map_geometry.project_plane_matrix(pts, normal)`

Relevant commit: https://github.com/pmgbergen/porepy/commit/3519fb8127680b296e11728337ba85450704249a#diff-77d93977371ccad207510d53c2c1fa3c

**Comment by keileg** [comment]
Thanks; I'll look into it.

The unit tests must be expanded as well.

**Comment by keileg** [comment]
Should be resolved by an upcoming PR. 

For reference, it is most often more convenient to do 3d ploting (also of grids) in paraview instead of matplotlib.
