### ISSUE TITLE
Uncessesary requirement: Networkx

### ISSUE THREAD

**Issue by rbe051** [pmgbergen/porepy#332]
Am I right that we have abandoned networkx? In that case, it should be removed from requirements.txt and requirements-dev.txt

**Comment by keileg** [comment]
I tried to do that some months ago. There are some residual dependencies somewhere, for instance related to geometry computations. I wrote those functions, and although it may be possible to implement an alternative to nx, I don't see it as an easy option. So until someone feels brave enough to do that, networkx should stay.

**Comment by rbe051** [comment]
That's a valid point! Then it stays
