### ISSUE TITLE
Implicit pymetis package call in /tutorials/mpsa.ipynb

### ISSUE THREAD

**Issue by ScottHMcKean** [pmgbergen/porepy#339]
Dear PM team,

Your Porepy package is F*ing awesome. Well done. I'm going to be using it and some of the fracture network to VTK filters for the last portion of my PhD and am incredibly grateful for the well crafted, GPL licensed code. 

Also, very minor issue - the pymetis package isn't explicitly imported in the mpsa tutorial, or some others. Might want to throw an explicit import or at least an assert at the top of the notebook to warn users.

Let me know if I can help with testing / development in any minor capacity.

**Comment by keileg** [comment]
Thank you for the kind words and encoragement!

We'll try to fix the pymetis import. pymetis is not really needed for anything, but if available, it is very useful at certain points in the code. Still, it is not a pretty prat of the code, and the import warning is indeed annoying. 

With regards to your project, I guess some comments on the status of the code could be useful: If you plan to do 2d networks, most of the code should work reasonably well - in particular meshing is in our experience quite stable for these problems. 3d meshing is also quite good, but many more things can go wrong compared to in 2d, so you may need to be a bit more cautious there. Of course, cell count and computational cost explodes when going to 3d. The numerics implemented should work, but again, the more complex the problems get, the more likely it is you need to take some special care to make simulations stable - and I am not sure exactly what I mean by that in a general case.

**Comment by ScottHMcKean** [comment]
Thanks, I'll try and run the meshing and fracture network stuff soonish (several other components to my research have to get done first)! I'll try and document as a go from a novice perspective :)

**Comment by OmarDuran** [comment]
The issue has already been resolved.
