### ISSUE TITLE
strange behaviour in intersecting fractures

### ISSUE THREAD

**Issue by alessiofumagalli** [pmgbergen/porepy#34]
```python
from porepy.viz import exporter                                       
from porepy.fracs import importer

mesh_kwargs = {}                                                                 
mesh_kwargs['mesh_size'] = {'mode': 'constant', 'value': 0.25, 'bound_value': 2} 
gb, _ = importer.from_csv("single.csv", mesh_kwargs)
exporter.export_vtk(gb, 'grid')
```

where the csv file is
```shell
FID,START_X,START_Y,END_X,END_Y                                                  
1,0.5,0,0.5,1                                                                    
3,0.75,0.5,0.75,1                                                                
4,0.49,0.625,0.75,0.625                                                          
5,0.49,0.62,0.75,0.62
```

**Comment by rbe051** [comment]
which branch are you on? I get the error message: ValueError: Start and endpoint of line should be                                 different

**Comment by alessiofumagalli** [comment]
Yes, with the develop branch I get the same error. I'm on my branch. However, if you check the points they are different..

**Comment by alessiofumagalli** [comment]
sorry my problem, use the following minimal example instead
``` python
from porepy.viz import exporter                                       
from porepy.fracs import importer

mesh_kwargs = {}                                                                 
mesh_kwargs['mesh_size'] = {'mode': 'constant', 'value': 0.25, 'bound_value': 2} 
domain = {'xmin': 0, 'xmax': 1, 'ymin': 0, 'ymax': 1}                            
gb = importer.from_csv("single.csv", mesh_kwargs, domain)
exporter.export_vtk(gb, 'grid')
```

**Comment by keileg** [comment]
I played with the tolerance, to no effect. My guess is a bug in the
intersection algorithm. I can do some digging.

**Comment by keileg** [comment]
@alessiofumagalli 
The behavior still looks strange to me, but: You are aware that you are asking to mesh a fracture that lies along the boundary of the domain? So even if we created a mesh, any numerics would be dubious. One possible solution is that the domain computation in `importer` uses some thresholding.

Nevertheless, I'll have a look at what happens in the splitting, it look like the algorithm enters some sort of a death spiral.

**Comment by keileg** [comment]
Modulo the above comment: Can you take a look at branch fix_issue_34, and see if it brings you further?

Also note that this branch introduce logging in some comp_geom functions. It is not perfect, and requires some tuning as to the levels of severity, but already very useful.

**Comment by keileg** [comment]
I think I will merge branch fix_issue_34 tonight. Let me know if it fix what you need, or not.

**Comment by alessiofumagalli** [comment]
Are you sure it worked? I see the same problem..

**Comment by keileg** [comment]
With the current status of develop, everything works for me.

**Comment by keileg** [comment]
Can I close?
