### ISSUE TITLE
create a persistent mybinder launcher

### ISSUE THREAD

**Issue by yunkb** [pmgbergen/porepy#350]
Dear admin, 
Here below there is doc for creating a mybinder 
https://mybinder.readthedocs.io/en/latest/introduction.html#preparing-repositories
I would suggest to register you to https://notebooks.gesis.org/hub/home. It offers one free server to lunch your code by users without any installation, just web interface.
Here https://github.com/yunkb/porepy/blob/develop/environment.yml. I start to edit the .ylm environment where one can combine conda (miniconda) and pip dependency. 
Setup.py is update https://github.com/yunkb/porepy/blob/develop/setup.py to allow mybinder to install it automatically. I follow https://github.com/binder-examples/setup.py/blob/master/setup.py.
To install porepy after dependency or add custom ones (previous version of gmsh), in this file:
https://github.com/yunkb/porepy/blob/develop/postBuild.
If there are any dependency from apt repo of base image, please add them in a apt.txt, 
Best
Davide

**Comment by keileg** [comment]
Thanks. We may look into this at some point, but for the time being, we do not have resources to go further.
