### ISSUE TITLE
different behaviour of face_cells among python versions

### ISSUE THREAD

**Issue by alessiofumagalli** [pmgbergen/porepy#39]
Sorry I cannot provide a simple example, see the branch update_coarsening.

It seams that with different version of python the map between face (of higher dimension) to cell (of lower dimension) changes during the runs.

Moreover with version 3.5 and 2.7 the result is not stable, sometimes the tests work and sometimes not. So far, only 3.6 is stable with that respect.

This is a major problem with testing for different python versions.

**Comment by keileg** [comment]
Is the problem that you cannot know the ordering of items in cell-face relations, and thus you cannot hard code a 'truth' to use for testing?

Let's have a look when you get back.

**Comment by alessiofumagalli** [comment]
In the current version of the branch (ready to be merged in the develop) some tests are run only with some version of python. I can close the issue, which is still present in the code but it isn't an error.
