### ISSUE TITLE
Allow fractures to hit edges in bounding box during meshing

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#4]
Boundaries of parameter subdomains (e.g. aquifer/aquitard, under and overburden) are conveniently introduced by fracture planes. However, these can currently not extend to the edges of the bounding box, as the latter is tacitly assumed not to be intersected by other objects. 

The modification will require reconfiguration of the way the boundary is introduced in the meshing.

**Comment by keileg** [comment]
@IvarStefansson was this resolved by #59?

**Comment by IvarStefansson** [comment]
Yes.
