### ISSUE TITLE
Update installation instructions on next PorePy release

### ISSUE THREAD

**Issue by haakon-e** [pmgbergen/porepy#429]
The installation instructions should be updated when the next PorePy version is released.

The installation instructions in `Readme.md` should reflect that `poetry` is the preferred way to install dependencies.

The same applies for the instructions in `Install.md`. E.g:
* Installation on Linux (and Windows)
* Optional python packages for faster runtimes (could mention e.g. Intel-numpy, etc.)
* gmsh instructions

**Comment by keileg** [comment]
Resolved by #447
