### ISSUE TITLE
Missing faces (cells?) on fractures

### ISSUE THREAD

**Issue by rbe051** [pmgbergen/porepy#43]
I came over a case where a face in the 3D grid is missing. The face should be a fracture face. The face exist in the 2D grid (as a cell), however, the 2D cell does not have a mapping to any face in the 3D domain. I have checked that it is not any problem with the mapping, and indeed the 3D face does not exists. I assume this also means that the two cells that should be connected to the face (note that this is before we split the grid) are also missing. 

Either, we are not reading the output from gmsh improperly, or gmsh removes this cell for some reason...

```python
import numpy as np

from porepy.fracs import fractures, meshing
from porepy.viz.exporter import export_vtk


def create_fractures(data):
    data = np.atleast_2d(data)
    centers = data[:, 0:3]
    maj_ax = data[:, 3]
    min_ax = data[:, 4]
    maj_ax_ang = data[:, 5]
    strike_ang = data[:, 6]
    dip_ang = data[:, 7]
    if data.shape[1] == 9:
        num_points = data[:, 8]
    else:
        num_points = 16 * np.ones(data.shape[0])

    frac_list = []

    for i in range(maj_ax.shape[0]):
        frac_list.append(fractures.EllipticFracture(centers[i, :],
                                                    maj_ax[i],
                                                    min_ax[i],
                                                    maj_ax_ang[i],
                                                    strike_ang[i],
                                                    dip_ang[i],
                                                    num_points[i]))
    fracture_network = fractures.FractureNetwork(frac_list)
    return fracture_network


frac_list = np.array([[2000, 2000, 2000, 1500, 1500, 0, 100, 80],
                      [1800, 1800, 2150, 700, 700, 0, 170, 70],
                      [2650, 2200, 1700, 850, 850, 0, 130, 70],
                      [2100, 2100, 2000, 1000, 1000, 0, 60, 80]])

box = {'xmin': 0, 'ymin': 0, 'zmin': 0,
       'xmax': 4000, 'ymax':  4000, 'zmax': 5000}
f = create_fractures(frac_list)
g = meshing.simplex_grid(f, box)
g.assign_node_ordering()

export_vtk(g, 'temp')
`

**Comment by rbe051** [comment]
This seems to have gotten worse with some update... A test for missing face_cells mapping has been added in the mesh-generation for the branch compressible_flow. All unit-tests were running fine after this. But then develop was merged into compressible_flow. After that, several tests fails due to missing face_cells mapping.

**Comment by keileg** [comment]
Any ideas of how rough the cells are? Or equivalently, does the problem disappear with mesh refinement?

**Comment by rbe051** [comment]
It seems to become better with mesh-refinement, but sometimes it also helps to create a coarser mesh

**Comment by keileg** [comment]
With the branch frac_mesh_3d (did some testing while working on another project), I get an error message from 

examples.example3.test_simple_networks.test_T_intersection_within_plane()

but only while running gmsh 2.11. For the newest version, I get no problems. The reason for testing 2.11 was that later versions are less stable for our purposes when the fracture geometry is complex.

Not sure if this leads us anywhere good, but I will keep digging.

**Comment by keileg** [comment]
Update: Gmsh 2.15 and newer seems to be good. 

I will create a workaround that gives a warning, rather than error, if this issue occurs. It will then be up to the user to decide on how strict to observe this.

**Comment by keileg** [comment]
We should retry newer versions of gmsh now that the new fracture meshing is more stable. Todo.

**Comment by rbe051** [comment]
Can confirm that this is indeed a bug in gmsh. I also tried with the newest gmsh, but that still for some cases. If you want to see a plot, I can show you tomorrow.

**Comment by keileg** [comment]
I have filed a report on Gmsh.

**Comment by rbe051** [comment]
For completeness I add here the script that did not run in the updated version of gmsh
```python
import numpy as np
import scipy.sparse as sps

from porepy.fracs import meshing
from porepy.fracs.fractures import EllipticFracture, FractureNetwork
from porepy.viz.exporter import Exporter


def create_mesh(degrees = True):

    data = np.array([0, 0, 0, 2, 2,  0, 20, 80, 20])
    box = {'xmin': -2, 'ymin': -2, 'zmin': -2,
           'xmax': 2, 'ymax':  2, 'zmax': 2}
    data = np.atleast_2d(data)
    centers = data[:, 0:3]
    maj_ax = data[:, 3] 
    min_ax = data[:, 4]
    maj_ax_ang = data[:, 5] * ( 1 - degrees + degrees * np.pi / 180)
    strike_ang = data[:, 6] * ( 1 - degrees + degrees * np.pi / 180)
    dip_ang = data[:, 7] * ( 1 - degrees + degrees * np.pi / 180)
    num_points = data[:, 8]
  
    frac = EllipticFracture(centers[i, :],
                                                    maj_ax[i],
                                                    min_ax[i],
                                                    maj_ax_ang[i],
                                                    strike_ang[i],
                                                    dip_ang[i],
                                                    num_points[i])
    frac_network = FractureNetwork([frac])
    mesh = meshing.simplex_grid(frac_network, box, ensure_matching_face_cell=False,
                                h_ideal=.5, h_min=.01)

    return mesh

gb = create_mesh()
```

**Comment by keileg** [comment]
This issue appears to have been fixed by the introduction of Gmsh 4.
