### ISSUE TITLE
make a tunnel or borehole geometry in a domain; neighboring cells of a cell

### ISSUE THREAD

**Issue by MiniSkull** [pmgbergen/porepy#430]
Hi!
Sorry to bother you!

I have two questions when I use PorePy.
Q1:
If I want to make a convex geometry (e.g., tunnel, borehole) in a 3d computational domain, is it possible? I want to keep matrix elements in the geometry.
Q2: Is there any function available in PorePy than I can use directly to get all neighboring cells of a cell?

Thanks!
Best regards,
Jin

**Comment by alessiofumagalli** [comment]
Dear Jin,

we are glad you are using pp, here the answers.

A1: you can construct the mesh in gmsh and import it in porepy
A2: not directly, but you can use a combination of `cell_faces` and its transpose. 
I suggest this `cell_cells = (g.cell_faces.T*g.cell_faces).astype(np.bool)`

If something is not clear feel free to ask, best regards.
Alessio

**Comment by MiniSkull** [comment]
Thanks for your quick reply.

I still do not understand A1.
I know how to construct a mesh of a complex domain without fractures. 
If I get the mesh, what should I do next? 
Is there any tutorial showing how to import the mesh and combine it with fracture mesh?

For example, after I mesh fractures using the following scripts:
network = pp.FractureNetwork3d(disks)
network.to_vtk('fracture_network.vtu')
domain = {'xmin': 0.0, 'xmax': 50.0, 'ymin': 0.0, 'ymax': 50.0, 'zmin': 0.0, 'zmax': 50.0}
network.impose_external_boundary(domain)
network.find_intersections()
network.intersection_info()
network.split_intersections()
mesh_size_frac = 1.0
mesh_size_min = 1.0
mesh_args = {'mesh_size_frac': mesh_size_frac, 'mesh_size_min': mesh_size_min}
gb = network.mesh(mesh_args) # I think I should import the matrix mesh here...

Thanks!
Best regards,
Jin

**Comment by alessiofumagalli** [comment]
Hey, 

I suggest to have a look on the function dfm_from_gmsh in the file fracture_importer.py, you might need that.
Best regards

Alessio

**Comment by keileg** [comment]
A1: As @alessiofumagalli hints at, you will probably need to combine the porepy geometry specification with that of gmsh. When importing the .msh file, we depend on a very specific, and elaborate, naming scheme for the various geometric objects, so fractures, intersection lines and points, fracture tips etc. This code is complex, but it serves its purpose. When you call network.mesh(), all the necessary geometric information is found, and written to a .geo file, gmsh constructs the mesh in the background, the resulting .msh file is imported, and the mixed-dimensional porepy mesh is constructed.

If I understand correctly, what you want is to use this functionality, but combined with what to porepy is a non standard domain geometry, that is, not a polyhedron? From what I know, this has not been tried before, but it may still work. I would suggest that you open the .geo file in gmsh and do the modification of the geometry there, is that is meaningful - I have limited experience with gmsh beyond debugging porepy messing. After dumping the mesh, you can try to import it with pp.fracture_importer.import_from_gmsh (or something like that, I don't have access to the source code right now). This may work right away, if it doesn't, my guess would be that you would need to carefully define the physical name of the part of the domain boundary that you introduced. Again, I don't have the code in front of me, so I can't be very specific, but if you try with a box domain, and extract a cylinder or sphere, it should not be too hard to figure out what is needed. But to be clear, although my feeling is it should work, I cannot guarantee there is no incompatibility that I fail to see right now.

A2: see the function cell_connection_map (or perhaps a similar name, I forgot). It essentially does what Alessio indicated in his answer.

**Comment by MiniSkull** [comment]
Thanks for  your reply!
It will take me a while to understand your advice and comments . @keileg @alessiofumagalli 
Best regards,
Jin
