### ISSUE TITLE
Rolling boundaries - in bc

### ISSUE THREAD

**Issue by saeunnh** [pmgbergen/porepy#452]
I've been looking at some old(er) code in where dir_x and dir_y is implemented in boundary conditions. Meaning either, x or y is fixed i.e. rolling boundary conditions. Would be helpful to include this in the code again.

**Comment by IvarStefansson** [comment]
I believe this can be obtained by setting something like
`BC.is_dir[ind_fixed, faces] = True`
`BC.is_neu[ind_fixed, faces] = False`
`BC.is_dir[ind_free, faces] = False`
`BC.is_neu[ind_free, faces] = True`

**Comment by rbe051** [comment]
Yes, Ivar is correct. To expand the answer slightly for possible future questions: 
The easiest way to set the rolling conditions to, e.g., the left boundary is:
```python
bc = pp.BoundaryConditionVectorial(g) # assigns all boundaries to Neumann
bc.is_dir[0, indices_of_left_boundaries] = True # Set Dirichlet to the x-component (index 0) to the left boundaries.
bc.is_neu[0, indices_of_left_boundaries] = True # Remember to remove the Neumann tags of the same faces.
```

If you wan to have rolling conditions that do not align with the Cartesian coordinate system that is also possible, but more complicated. You then have to transform the coordinate system on the boundary faces by setting bc.basis. bc.basis defines the coordinate system for each face (defaults to the identity matrix). To set a rolling condition on a 45 degree slope you set 
```python
# Initiate boundary conditions
bc = pp.BoundaryConditionVectorial(g)
# Define basis transformation for the boundary:
theta = np.pi / 4 # Rotate the boundary by theta radians
# Define the basis transformation as a matrix:
R = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
# Extract the normal and tangential basis
n = R.dot(np.array([[0, 1]]).T)
t = np.array([n[1], -n[0]])

for f in face_indices_that_are_rolling:
    # Dirichelt and Neumann basis
    bc.basis[0, :, f] = n.T # Normal component
    bc.basis[1, :, f] = t.T # Tangential component

bc.is_dir[0, face_indices_that_are_rolling] = True # Set no displacement in normal direction
bc.is_neu[0, face_indices_that_are_rolling] = False # Neumann is True by default.
```
