### ISSUE TITLE
Viscosity missing

### ISSUE THREAD

**Issue by rbe051** [pmgbergen/porepy#46]
Viscosity should be added to the parameter class. Also need the figure out the best way to include in the equations.

**Comment by keileg** [comment]
Ideally, it should be a function, not a constant.

**Comment by rbe051** [comment]
you mean, e.g., a function of pressure? In this case, this is not exclusive for the viscosity, e.g., for time-dependent problems the bc_val should also be a function depending on time

 I think we have two options:
1: This should go into a larger restructuring of the Parameter class to allow us to specify functions
2: The parameter class only contains numbers, and it is left to the user to update the parameters, e.g., calling  param.set_bc_val(...)  at each time step.

I think I prefer the second alternative.

**Comment by keileg** [comment]
I think I agree with you, but you may need to revisit this when you want to write a solver for coupled flow and transport, with temperature dependent viscosity. But no 2 should suffice for now.

**Comment by rbe051** [comment]
Ok, so I will add number 2 for now, and see how this turns out

**Comment by keileg** [comment]
Sounds good.

**Comment by keileg** [comment]
Can we close this now? And reconsider if we dive further into pressure + temperature?

**Comment by rbe051** [comment]
yes, we can close it. Will probably have to reopen when we wish to add constitutive laws, but this will be a problem for any of the parameters
