### ISSUE TITLE
Use consistently primary/secondary to refer to grids and data dictionaries

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy#478]
In many places, there is extended use of `g_h` and `g_high` to refer to the higher-dimensional grid (same for `d_h` and `d_high`) and `g_l` and `g_low` to refer to the lower-dimensional grid (same for `d_l` and `d_low`). Ideally, we should homogenize these references using `g_primary` (`d_primary`) and `g_secondary` (`d_secondary`), respectively.

**Comment by keileg** [comment]
I will try to help out. See my comments in #477, though: We can afford some pragmatism in how aggresive we are in rooting out the old terminology.

**Comment by keileg** [comment]
This should to a large degree have been solved in #673, but we'll keep it open for a while as a reminder.
