### ISSUE TITLE
FaceTag.DOMAIN_BOUNDARY or FaceTag.BOUNDARY

### ISSUE THREAD

**Issue by alessiofumagalli** [pmgbergen/porepy#48]
In the case of single grid, at the end of the constructor this function is called
```python
update_boundary_face_tag()
```
which updates only the boundary faces with the tag BOUNDARY. However, in the case of grid bucket the faces at the boundary are also DOMAIN_BOUNDARY, while the BOUNDARY includes also the FRACTURE faces. Can I simply change the line in the previous function from:
```python
self.add_face_tag(bd_faces, FaceTag.BOUNDARY )
```
to
```python
self.add_face_tag(bd_faces, FaceTag.BOUNDARY | FaceTag.DOMAIN_BOUNDARY)
```

**Comment by rbe051** [comment]
I'm not sure what you try to achieve.
The definition of BOUNDARY is any face that is only connected to 1 cell.
BOUNDARY = DOMAIN_BOUNDARY & FRACTURE & TIP

setting BOUNDARY | DOMAIN_BOUNDARY should therefore not give a different result from setting only BOUNDARY

**Comment by rbe051** [comment]
Nevermind, I think I understand what you want to do. Do you want to add the FaceTag DOMAIN_BOUNDARY to a single grid ? In that case, I belive the statement
```python
self.add_face_tag(bd_faces, FaceTag.BOUNDARY | FaceTag.DOMAIN_BOUNDARY)
```
is correct

**Comment by alessiofumagalli** [comment]
yes, because is DOMAIN_BOUNDARY where I put my bc and not BOUNDARY

**Comment by alessiofumagalli** [comment]
If I do the change one test (about the face tag) fails, I fix it. OK?

**Comment by rbe051** [comment]
I then agree. Go ahead and change it

**Comment by rbe051** [comment]
in meshing line 231

    for gs in grids:
        for g in gs:
            g.remove_face_tag([True] * g.num_faces, FaceTag.DOMAIN_BOUNDARY)
