### ISSUE TITLE
Unit test for Mixed VEM fails 

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#49]
test.unit.test_dual_vem.BasicsTest.test_dual_vem_2d_ani_cart_surf() fails occasionally, with no clear reasons. See e.g. Travis build 482. 

Apparently, the test alternates between two different answers, with one being the identified correct one.

**Comment by keileg** [comment]
I've had a look at this, but found nothing at all.  There are no obvious places that can should lead to random behavior as we observe.

I'm quite sure this is not the problem, but is the way the permeability is given (xy coordinates, rather than rotated) the correct one?

**Comment by keileg** [comment]
git bisect traced it down to commit bd269af608ba17eea01c40bbc03dba9a3c9a21eb , which did an update to the way (the non-unique) tangent vectors for a point cloud is computed (comp_geom.compute_tangent()). The changed version should be more robust, but will compute a different tangent vector from before.

@alessiofumagalli :Will this make a difference to the result? I suppose the discretization matrix is independent of the tangent?

**Comment by alessiofumagalli** [comment]
Hi, yes it should be independent from the tangent vector. I'll try to test your new way, is it in a new branch?

**Comment by keileg** [comment]
frac_mesh_3d

**Comment by alessiofumagalli** [comment]
it's very strange, I installed both python 2.7 and 3.5 but on my laptop the test works perfectly. I'm in the develop branch which failed on Travis. still not clear how to reproduce the error on Travis.

**Comment by keileg** [comment]
After merging in #60, it seems the error has disappeared, and travis looks happy as well.

I will close this one now, and reopen if the ghost shows up again.
