### ISSUE TITLE
The new exporter broken for 3d Cartesian grids

### ISSUE THREAD

**Issue by rbe051** [pmgbergen/porepy#496]
```python
import porepy as pp
import numpy as np

g = pp.CartGrid([10, 10, 10], [1, 1, 1])
g.compute_geometry()
exporter = pp.Exporter(g, "temp")
exporter.write_vtu()
```

causes: AttributeError: 'list' object has no attribute 'astype'
in meshio called from line 804 in exporter.py
```python
meshio.write(file_name, meshio_grid_to_export, binary=self.binary)

```

**Comment by keileg** [comment]
Sounds like a missing `np.asarray`. I will take care of it.

**Comment by keileg** [comment]
@rbe051 I cannot reproduce the error. Which version of `meshio` do you use?

**Comment by rbe051** [comment]
I am using meshio==4.2.2

**Comment by rbe051** [comment]
it looks like it runs in meshio-4.3.6

**Comment by keileg** [comment]
There was some updates there, yes. Sigh.
