### ISSUE TITLE
Convert mpfa and mpsa to pure class-based methods

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#5]
@IvarStefansson @rbe051 The emerging structure, where the discretization is provided by module-level functions, but also with a class wrapper, is confusing. I think we do want to keep the classes, both to be compatible with the approach in VEM, and also for convenient handling of mixed-dimensional problems. Also note that the classes are shells that do not store data (thus they are quite equivalent with functions, but appears more elegant to me).

Do you see any downside with dropping the functions, and leave a single, class, entry-point to the discretizations?

**Comment by rbe051** [comment]
No, I don't see any downside with this.

**Comment by keileg** [comment]
Then I will restructure mpfa.py and mpsa.py quite a bit. I will likely also move the poro-elastic part into a separate file.

Time frame: Some time after Ivar's updates fv_coupling is merged.

**Comment by keileg** [comment]
It turns out that moving everything into classes will require that we get inheritance exactly right, since biot and mpsa have some files in common. I'm not going to do this now; one could argue that we need not use the classes at all anyhow. 

I put this on hold for a while; it is not closed, but dormant.

**Comment by keileg** [comment]
On second thought, I close this. Perhaps to be reopened at some point.
