### ISSUE TITLE
Improved identification of fractures

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#50]
Identification of fractures is now done by the fracture index, which is assigned in an as systematic way as possible, but is still not robust. Should be fixed.

**Comment by alessiofumagalli** [comment]
interesting, could you give a short example? or point where to find one?

**Comment by keileg** [comment]
It's a todo, mostly related to how the FractureNetwork deals with its components. Probably, we should tie this closer to id() or similar, but there may be issues here related to copying of fractures and other modifications. 

For the moment, this is an intention of purpose, and a warning this is not a robust part of the code.
