### ISSUE TITLE
update example that uses reconstruct_local_displacement_jump

### ISSUE THREAD

**Issue by haakon-e** [pmgbergen/porepy#501]
https://github.com/pmgbergen/porepy/blob/acfbe96b8e26a16de1d0e2fba1e525e39d0ecee2/test/common/contact_mechanics_examples.py#L170-L172

This line of code should be updated since the code for `reconstruct_local_displacement_jump` is updated to require the `projection` operator as input. See:

https://github.com/pmgbergen/porepy/blob/acfbe96b8e26a16de1d0e2fba1e525e39d0ecee2/src/porepy/models/contact_mechanics_model.py#L283-L288

I'm guessing this is code either @keileg or @IvarStefansson have looked at recently?
Ideally, I guess the example itself should be part of the test suite? (to ensure that it always works)

**Comment by keileg** [comment]
Thanks. I'll take care of it.

**Comment by keileg** [comment]
I think #503 should resolve this, at least for now. 

In the longer term, I think the method `_compute_aperture`  in test/common, 
https://github.com/pmgbergen/porepy/blob/acfbe96b8e26a16de1d0e2fba1e525e39d0ecee2/test/common/contact_mechanics_examples.py#L157-L180

should either be moved to the `ContactMechanicsModel` or deleted. Opinions @IvarStefansson
