### ISSUE TITLE
exporter: convert boolean data to int

### ISSUE THREAD

**Issue by haakon-e** [pmgbergen/porepy#502]
It seems like meshio doesn't approve of boolean data being passed to the vtu-exporter. Sometimes, it's convenient to keep data in `d[pp.STATE]` as boolean arrays. Could we think about automatically converting boolean data to integer data internally in `pp.Exporter` only? (e.g. using [np.ndarray.astype](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html))

How complicated would this be? @alessiofumagalli @keileg

**Comment by keileg** [comment]
Should be relatively easy. I can have a look.

**Comment by keileg** [comment]
@haakon-e Do you have an example of an array that cannot be exported - or do you think of lists? 

I did a simple test with `np.array([...], dtype=bool)`, and this seemed to work. From what I know about `meshio`,  all (most?) numpy data types should work.

**Comment by haakon-e** [comment]
Hmm. I'll try to reduce my code to a simple example (but my array was constructed exactly as your test suggested). Let me first try to update meshio etc and get back to you if it doesn't resolve the issue.

**Comment by keileg** [comment]
@haakon-e: Any updates on this one - or can I close?

**Comment by haakon-e** [comment]
I see this have slipped me. Closing is fine.
