### ISSUE TITLE
Time consuming fracs.meshing.split_fractures()

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#51]
For large problems, the split_fractures part of the meshing algorithm takes exceedingly long time. Below follows run script an output to illustrate the problems.

Run with branch frac_mesh_3d, commit e765a57 .

##### Run script ##########
import numpy as np

from porepy.fracs import extrusion, importer, meshing
from porepy.fracs.fractures import Fracture, FractureNetwork
from porepy.viz import exporter

np.random.seed(7)
pt, edges = importer.fractures_from_csv('barely-connected_4pp.log
[barely-connected_4pp.log](https://github.com/pmgbergen/porepy/files/1427571/barely-connected_4pp.log)
')
fractures = extrusion.fractures_from_outcrop(pt, edges)

f = fractures

network = FractureNetwork(f)
network.tol = 1e-5
network.find_intersections()
network.split_intersections()

gb = meshing.simplex_grid(network=network, h_ideal=0.5, h_min=0.1, verbose=1, ensure_matching_face_cell=False)

########## Output ########################

Construct mesh
Use existing intersections
Use existing decomposition
Gmsh processed file successfully

Grid creation completed. Elapsed time 1.3945231437683105

Created 1 3-d grids with 81662 cells
Created 66 2-d grids with 16949 cells
Created 82 1-d grids with 234 cells

Done. Elapsed time 75.7353572845459
Assemble in bucket
/home/eke001/Dropbox/workspace/python/porepy/src/porepy/fracs/meshing.py:404: UserWarning: Found inconsistency between cells and higher
                          dimensional faces. Continuing, faces crossed
  dimensional faces. Continuing, faces crossed''')
Done. Elapsed time 10.409296751022339
Compute geometry
Done. Elapsed time 0.6946992874145508
Split fractures
Done. Elapsed time 497.07970118522644
Mesh construction completed. Total time 583.9497916698456

**Comment by rbe051** [comment]
my timing. Notice the extreme time consumption for grid creation:
 Construct mesh
Use existing intersections
Use existing decomposition
Gmsh processed file successfully

Grid creation completed. Elapsed time 3837.416199207306

Created 1 3-d grids with 75863 cells
Created 66 2-d grids with 15449 cells
Created 82 1-d grids with 234 cells

Done. Elapsed time 3901.5071873664856
Assemble in bucket
/home/runar/uib/porepy/src/porepy/fracs/meshing.py:404: UserWarning: Found inconsistency between cells and higher dimensional faces. Continuing, faces crossed  dimensional faces. Continuing, faces crossed''')
Done. Elapsed time 15.073590278625488
Compute geometry
Done. Elapsed time 0.537250280380249
Split fractures
Done. Elapsed time 446.250691652298
Mesh construction completed. Total time 4363.393520832062

**Comment by keileg** [comment]
For reference, the time consumption in grid creation can be drastically reduced by upgrading to numpy >=1.13, or manually installing the faster version of unique on integer arrays, see https://github.com/pmgbergen/porepy/blob/develop/Install.md for details.

**Comment by rbe051** [comment]
upgrading numpy solved this problem

**Comment by rbe051** [comment]
I started looking into this now. The splitting time is now down in the range of bucket assembly. The most time consuming parts are slicing of sparse matrices. More or less the only update to the code has so far been to move from slicing matrices using A[:, ind] to slicing them using the A.indptr, A.indices and A.data. See branch  optimize_split_grid.

**Comment by keileg** [comment]
Looks good. slicing of sparse matrices is indeed not effective.

Do you plan more changes? If not, I can merge back into frac_mesh_3d, and this will again be merged into develop pretty soon.

**Comment by rbe051** [comment]
I will have a look on it tomorrow. I don't think I will do any big changes, but if I find some other matrix slicing or equivalent I will change it

**Comment by keileg** [comment]
Sounds good. Thanks a lot!

**Comment by rbe051** [comment]
I think the latest commit 305296326d87e054d1671cfa7a5fa7820e86c0a9 in the optimize split fractures branch has an acceptable runtime. Still possible for some improvement though, but will maybe look at it at a later stage if it becomes a large problem

**Comment by keileg** [comment]
Can I then merge back into frac_mesh_3d?

**Comment by rbe051** [comment]
yes

**Comment by keileg** [comment]
For reference, this branch was merged into frac_mesh_3d in commit 5e5f48d and then deleted. Pull request and merge would have been cleaner.
