### ISSUE TITLE
extract pressure gradient of each cell

### ISSUE THREAD

**Issue by MiniSkull** [pmgbergen/porepy#516]
Hi!
I am trying to simulate fluid flow through fractures in fractured rock using the two-point flux approximation. I have two questions that confuse me.
1.  It is easy to extract matrix pressure (or fracture pressure) of each cell using _d[pp.STATE]['pressure']_.  Is there an easy way to extract the pressure gradient of each cell?
2. I can extract the flux using _flux = d[pp.DISCRETIZATION_MATRICES]["flow"]["flux"]_. Is it correct to extract  the flux on boundary faces using  _flux[b_faces]_?

Thanks!
Best regards,
Jin

**Comment by keileg** [comment]
Hi,

1. The numerical methods available in PorePy have no cell-wise notion of gradients - mathematically speaking, the solution is not guaranteed to have sufficient regularity for such a gradient to exist. Thus, there is no discrete gradient operator readily available (some of the methods have gradient-like operators on subcells, but you don't want to use those). There are however ways of reconstructing cell-wise gradients: In our experience, an accurate option is to define a cell-wise flux field, and then compute the pressure gradient which corresponds to this flux field. We use this in a spin-off project, specifically see https://github.com/jhabriel/mixdim-estimates/blob/develop/src/mdestimates/_pressure_reconstruction.py for an implementation.

2. This depends on whether you refer to an external boundary, or a boundary to a lower-dimensional domain (from host medium to fracture, or from fracture to fracture intersection). For external boundaries, the answer is yes, you can use `flux[bound_faces]`. For internal boundaries, the flux is stored as a mortar flux, so you will need to first get the edges (in the `GridBucket` sense) of the subdomain in question, then get the fluxes, and finally, if you need the fluxes on the subdomain, project them. The code will roughly be

``` python
for e, d in gb.edges_of_node(g):
   flux = d[pp.STATE]['mortar_flux']  # .. or whatever keyword you use
   proj = d['mortar_grid'].mortar_to_primary_int()  
   flux_on_subdomain = proj * flux
```

**Comment by keileg** [comment]
I will close this one, feel free to reopen if relevant.
