### ISSUE TITLE
Unexpected behavior when Ad_array is multiplied with numpy array

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#526]
The implementation of multiplication between `Ad_array `and `np.ndarray ` seems to assume that the numpy array is 1d. For 2d arrays, standard matrix multiplication should instead be added (same probably applies to many other operations).

**Comment by keileg** [comment]
The behavior reflects how multiplication is interpreted for `numpy` arrays (it is not a dot product). For the expected matrix-vector product, wrap the array as a sparse matrix instead.

If this turns out to be a consist problem, we'll need to implement dot product for Ad arrays.

**Comment by jhabriel** [comment]
My two workarounds when it comes to this issue are:

1. Put the 'Ad_array' to the left and the 'np.ndarray' to the right of the '*' operation.
2. Convert your 'np.ndarray' into a (sparse) diagonal matrix

The first option is easy to implement, but you will often lose readability when writing large expressions. The second option requires an extra step but usually preserves the mathematical structure of the expression.

P.D.: No need to reopen the issue, just wanted to share my "tricks".
