### ISSUE TITLE
Error create vtk file using paraview_exporter

### ISSUE THREAD

**Issue by MB209** [pmgbergen/porepy#533]
Hi!
I try to create a vtk file from an code. But I can not found a solution. How can I solve this problem.

Many Thanks

Code:
 
import porepy as pp
import numpy as np
from scipy.sparse.linalg import spsolve
f1=pp.Fracture(np.array([[0,1,1,0], [0,0,1,1], [0,0,0,0]]))
f2=pp.Fracture(np.array([[0,0,0,0], [0,1,1,0], [0,0,1,1]]))
network=pp.FractureNetwork3d([f1,f2])
gb=network.mesh({'mesh_size_frac': 0.1, 'mesh_size_bound': 1, 'mesh_size_min': 0.01})
diffusion_discr=pp.Mpfa('flow')
accumulation_discr=pp.MassMatrix('flow')
for g, d in gb:
    pp.initialize_default_data(g, d, 'flow')
    d[pp.PRIMARY_VARIABLES] = {'p': {'cells': 1}}
    d[pp.DISCRETIZATION] = {'p': {'accumulation': accumulation_discr, 'diffusion': diffusion_discr}}
for e, d in gb.edges():
    g_l, g_h = gb.nodes_of_edge(e)
    mg = d['mortar_grid']
    data = {'normal_diffusivity': 1}
    pp.initialize_data(mg, d, 'flow', data)
    d[pp.PRIMARY_VARIABLES] = {'mortar_flux': {'cells': 1}}
    interface_discr = pp.RobinCoupling('flow', diffusion_discr, diffusion_discr)
    d[pp.COUPLING_DISCRETIZATION] = { 'interface_flux': {g_h: ('p', 'diffusion'), g_l: ('p', 'diffusion'), e: ('mortar_flux', interface_discr)}}
    
assembler = pp.Assembler(gb)
assembler.discretize()
A, b = assembler.assemble_matrix_rhs()
p = spsolve(A, b)
assembler.distribute_variable(p)
paraview_exporter = pp.Exporter(gb, file_name='foo')
paraview_exporter.write_vtk('p')
 
 
 
Error message:

/home/xmg/anaconda3/lib/python3.8/site-packages/porepy/viz/exporter.py:1012: NumbaPerformanceWarning: np.dot() is faster on contiguous arrays, called on (array(float64, 1d, A), array(float64, 1d, C))
  angle = np.arccos(np.dot(normals[:, fi], reference))

 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-37ce4ea0c93a> in <module>
     27 assembler.distribute_variable(p)
     28 paraview_exporter = pp.Exporter(gb, file_name='foo')
---> 29 paraview_exporter.write_vtk('p')

AttributeError: 'Exporter' object has no attribute 'write_vtk'

**Comment by IvarStefansson** [comment]
As your error message says, the Exporter has no write_vtk method. After a fairly recent update, the method name is write_vtu.
