### ISSUE TITLE
T intersections

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#54]
Below included example on frac_mesh_3d leads to intersecting face pairs. Gmsh says

!! Found 108 pairs of faces are intersecting.

Self-intersection seconds:  0.113017
Writing nodes.
Writing faces.
Error   : ------------------------------
Error   : Mesh generation error summary
Error   :     0 warnings
Error   :     1 error
Error   : Check the full log for details
Error   : ------------------------------
Gmsh failed with status 256

CODE

from porepy.fracs import meshing
import numpy as np
from porepy.viz.exporter import export_vtk

def define_grid():
    """
    One horizontal and one vertical 1d fracture in a 2d matrix domain.
    """
    mesh_kwargs = {}
    mesh_size = 5e-1
    mesh_kwargs['mesh_size'] = {'mode': 'constant',
                        'value': mesh_size, 'bound_value': 1.2*mesh_size}
    mesh_kwargs['file_name'] = 'bounding_box_test'
    
    
    domain = {'xmin': 0, 'xmax': 1,
              'ymin': 0, 'ymax': 1,
              'zmin': 0, 'zmax': 1}
    f_1 = np.array([[.5,.5,.5,.5],
                    [.4,.5,.5,.4],
                    [0.2,0.2,.8,.8]])
    f_2 = np.array([[0,.8,.8,0],
                    [.5,.5,.5,.5],
                    [0.2,0.2,.8,.8]])#[0,0,1,1]])

    
    fracs = [f_1,f_2]
    gb = meshing.simplex_grid( fracs,domain,**mesh_kwargs)
    gb.assign_node_ordering()
    
    return gb

gb = define_grid()
export_vtk(gb, 'bounding_box_test_grid')

**Comment by keileg** [comment]
Fixed by 099e8f5
