### ISSUE TITLE
Broadcasting issue while evaluating ad expressions composed of ad variables with different sizes

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy#556]
**Description of the issue**
The current parsing process of ad expressions with ad variables having different degrees of freedom results in sizes of the Jacobian that may be undesired.

**MWE**
`gb = pp.meshing.cart_grid([], nx=[1, 1])`
`g = gb.grids_of_dimension(2)[0]`
`d = gb.node_props(g)`
`d[pp.PRIMARY_VARIABLES] = {"pressure": {"cells": 1}}`
`pp.set_state(d, {"pressure": np.zeros(g.num_cells)})`
`dof_manager = pp.DofManager(gb)`
`equation_manager = pp.ad.EquationManager(gb, dof_manager)`
`p = equation_manager.merge_variables([(g, "pressure")])`

`np_array = np.array([1, 2, 3])`
`ad_array = pp.ad.Array(np_array)`
`aux_variable = p + ad_array`
`expression = pp.ad.Expression(aux_variable, dof_manager)`
`expression_num = expression.to_ad(gb=gb)`

**Current output**
>> expression_num
Ad array of size 3
Jacobian is of size (1, 1) and has 1 elements

Note that `expression_num.val` has the right size. However, `expression_num.jac` is not broadcasted correctly, i.e., it does not take into account the size of `ad_array`.

**Expected output**
>> expression_num
Ad array of size 3
Jacobian is of size (3, 1) and has 3 elements

**Proposed workaround**
Far from elegant, the current workaround consists of broadcasting the expression manually.

First, create the broadcaster, this should be an `ad_matrix` to make things work:
`broadcaster = pp.ad.Matrix(sps.csr_matrix(np.ones_like(np_array)).reshape((-1, 1)))`

Now, rewrite the expression
`new_aux_variable = broadcaster * p + ad_array`
`new_expression = pp.ad.Expression(new_aux_variable, dof_manager)`
`new_expression_num = new_expression.to_ad(gb)`

The output is now the expected one:
>> new_expression_num
Ad array of size 3
Jacobian is of size (3, 1) and has 3 elements

**Comment by keileg** [comment]
I have thought more about this: What your example does is to expand a scalar quantity `p` to a vector. This is meaningful only for scalar Ad variables - if your grid had had `nc` cells, `nc > 1`, `p + ad_array` (where ad_array has a multiple of `nc` components) would not make sense. Thus, while I agree that the output from your example is unexpected, I'm not sure we want to implement implicit broadcasting for Ad variables that happen to live on a grid with one cell (note that there is a tacit but deep assumption in the whole framework that variables are related to grids). In my view, such an inconsistency betwen grids with 1 and multiple cells would be worse than the current behavior.

What do you think?

**Comment by jhabriel** [comment]
I agree @keileg. This is meaningful only for ad variables associated with one cell (which is quite rare to encounter in simulations anyway). No need to dig deeper into this. At least, we can now redirect to this issue if someone in the future struggles with the same problem.
