### ISSUE TITLE
Multiplication in AD

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#560]
Assembly fails in unpredictable ways as demonstrated by this example:

```
import porepy as pp
import numpy as np

gb, domain = pp.grids.standard_grids.grid_buckets_2d.single_horizontal(
    mesh_args=[2, 2], x_endpoints=None, simplex=False
)
grid_list = []
for g, d in gb:
    pp.initialize_data(
        g,
        d,
        "key",
        {
            "parameter": np.ones(g.num_cells),
            "mass_weight": np.ones(g.num_cells),
            "second_order_tensor": pp.SecondOrderTensor(np.ones(g.num_cells)),
            "bc": pp.BoundaryCondition(g),
        },
    )
    pp.set_state(d, {"var": np.zeros(g.num_cells)})
    pp.set_iterate(d, {"var": np.zeros(g.num_cells)})
    grid_list.append(g)
    d[pp.PRIMARY_VARIABLES] = {"var": {"cells": 1}}
for e, d in gb.edges():
    d[pp.PRIMARY_VARIABLES] = {}

dof_manager = pp.DofManager(gb)
eq_manager = pp.ad.EquationManager(gb, dof_manager)
var_ad = eq_manager.merge_variables([(g, "var") for g in grid_list])
param = pp.ad.ParameterArray(
    param_keyword="key",
    array_keyword="parameter",
    grids=grid_list,
)
mass_ad = pp.ad.MassMatrixAd("key", grid_list)
mpfa_ad = pp.ad.MpfaAd("key", grid_list)

# First two demonstrate non-commutability
eq_1 = pp.ad.Expression(var_ad * param, dof_manager, "equation 1", grid_order=grid_list)
eq_2 = pp.ad.Expression(param * var_ad, dof_manager, "equation 2", grid_order=grid_list)
# Left multiplication by flux requires parentheses
eq_3 = pp.ad.Expression(
    mpfa_ad.flux * var_ad * param, dof_manager, "equation 3", grid_order=grid_list
)
eq_4 = pp.ad.Expression(
    mpfa_ad.flux * (var_ad * param), dof_manager, "equation 4", grid_order=grid_list
)
# But left multiplication by mass is fine
eq_5 = pp.ad.Expression(
    mass_ad.mass * var_ad * param, dof_manager, "equation 5", grid_order=grid_list
)

eqs = [eq_1, eq_2, eq_3, eq_4, eq_5]
for i, eq in enumerate(eqs):
    eq_manager.equations = [eq]
    eq_manager.discretize(gb)
    try:
        eq_manager.assemble_matrix_rhs()
    except:
        print(f"Failed assembling eq {i+1}")
```

**Comment by IvarStefansson** [comment]
Thanks, @jhabriel, I expect this will be a really valuable clue for how to fix the issue!

**Comment by keileg** [comment]
First, thanks for the convenient script to reproduce the issue @IvarStefansson!

For `eq_2` The explanation given by @jhabriel is correct, but I fully agree that the current behavior is far from intuitive. I think this can be taken care of in the parsing of the operators, and will implement a fix.

eq_3 is more delicate: Essentially, the prescribed operation is of the form `A * B * C`, but from the types and sizes of `A`, `B` and `C` it is implied that the first multiplication is a matrix-vector product, while the second is an element-wise multiplication. For the whole expression to be meaningful it must be parsed from the right, but there is no way of knowing that without carefully inspecting the variables (note that if `C` has a size equal to number of rows in `A`, the parsing should work). This cannot be resolved locally when combining two operators, but would likely require a much more elaborate parsing of an `Operator` tree, including providing interpretation of what operators like `*` mean. I do not think this is something we want to do - it would require a huge effort and be prone to errors. The solution is therefore to use parentheses as you also indicate.

The error message, or lack thereof, for eq_3, is not helpful. I will improve on this.
