### ISSUE TITLE
T intersection of 2d planes

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#58]
Special case of T intersection of 2d planes. The intersection line is interpreted as a "boundary line" of the base of the T, possibly because it reaches the boundary of the other plane. This ultimately yields
    assert sorted_lines[0, 0] == sorted_lines[1, -1]
AssertionError
Happens for f_1 with both f_2 and f_3. but not f_4 (corner to corner):

def test_issue_56(): 
     
    domain = {'xmin': -2, 'xmax': 2, 'ymin': -2, 'ymax': 2, 
              'zmin': -2, 'zmax': 2} 
    mesh_size = {'mode': 'constant', 'value': .4, 'bound_value': 1} 
    kwargs = {'mesh_size': mesh_size, 'return_expected': True} 
     
    f_1 = np.array([[0, 1, 1, 0], [0, 0, 1, 1], [0, 0, 0, 0]]) 
    f_2 = np.array([[0, 1, 1, 0], [0, .5, .5, 0], [0, 0, 1, 1]]) 
    f_3 = np.array([[0, 1, 1, 0], [0.3, .5, .5, 0.3], [0, 0, 1, 1]]) 
    f_4 = np.array([[0, 1, 1, 0], [0, 1, 1, 0], [0, 0, 1, 1]]) 
    grids = meshing.simplex_grid([f_1, f_2], domain,**kwargs)

**Comment by keileg** [comment]
I get no problems with f_1 and f_3 (nor f_4) on develop. [f_1, f_2] is a problem, though.
