### ISSUE TITLE
Installing porepy package on PyCharm in Windows 11

### ISSUE THREAD

**Issue by qasim314** [pmgbergen/porepy#604]
Hi, It is an amazing package, from what I have read in the paper and specially for me doing PhD research in studying the transport of contaminants and water in fractured rocks. I'm trying to run one of your example code that involves importing porepy. I tried to install this package using pip and conda but it seems that it is not available with PyPl. I'm an average Python user and maybe I'm missing something. Could you please help on how to install 'Porepy' package in python 3.8 on windows 11?

**Comment by IvarStefansson** [comment]
Please confer the installation instructions: You need to obtain the source code, install dependencies (most are available using conda, the remainding packages require pip) and install porepy. The procedure is known to work on the combination Python 3.8 and Windows 10, while Windows 11 has not yet been tested to the best of my knowledge.

**Comment by qasim314** [comment]
Thanks it worked on Python 3.9, however I was not able to install this package on 3.8 py version.

**Comment by keileg** [comment]
AFAIK, there are no clear reasons why Python 3.8 should fail if 3.9 does not. Is it a specific package which is not available, or otherwise, how does the installation fail?

**Comment by keileg** [comment]
I will close this one, feel free to open should there be new developments.
