### ISSUE TITLE
Problems communicating with gmsh

### ISSUE THREAD

**Issue by L4student** [pmgbergen/porepy#61]
I installed porepy (from source using Python 2.7) and then followed-up by testing the build as suggested using the following commands:
```
pip install -r requirements-dev.txt
python setup.py test
```

However, the test gives the following error:

```
==================================== ERRORS ====================================
___ ERROR collecting examples/example8/test_advection_diffusion_coupling.py ____
ImportError while importing test module '/home/gary/porepy/examples/example8/test_advection_diffusion_coupling.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
examples/example8/test_advection_diffusion_coupling.py:139: in <module>
    gb = importer.from_csv(folder + 'network.csv', mesh_kwargs, domain)
src/porepy/fracs/importer.py:43: in from_csv
    return meshing.simplex_grid(f_set, domain, **mesh_kwargs)
src/porepy/fracs/meshing.py:90: in simplex_grid
    grids = simplex.triangle_grid(frac_dic, domain, **kwargs)
src/porepy/fracs/simplex.py:270: in triangle_grid
    return triangle_grid_from_gmsh(file_name, **kwargs)
src/porepy/fracs/simplex.py:288: in triangle_grid_from_gmsh
    **gmsh_opts)
src/porepy/grids/gmsh/gmsh_interface.py:469: in run_gmsh
    config = read_config.read()
src/porepy/utils/read_config.py:46: in read
    raise ImportError(s)
E   ImportError: Could not load configuration file for PorePy.
E   To see instructions on how to generate this file, confer help
E   for this module (for instance, type 
E     porepy.utils.read_config? 
E   in ipython)
------------------------------- Captured stdout --------------------------------
/home/gary/porepy/examples/example8/
============================ pytest-warning summary ============================
WC2 /home/gary/porepy/test/unit/test_doctests.py cannot collect 'test_suite' because it is not a function.
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
================= 1 pytest-warnings, 1 error in 139.03 seconds =================
```

**Comment by keileg** [comment]
It looks like it cannot find the path to Gmsh, probably because you have not defined the file porepy_config somewhere in $PYTHONPATH. See [install instructions](https://github.com/pmgbergen/porepy/blob/develop/Install.md)

**Comment by L4student** [comment]
So, I downloaded the gmsh binary and then performed the recommended steps, i.e., made a `porepy_config.py` file (with the content shown below) that I stored in `porepy` directory, followed by adding `porepy` directory to the `PYTHONPATH` in `.bashrc` file as shown below:

**Inside .bashrc:**
`export PYTHONPATH=${HOME}/porepy`

**Inside porepy_config.py:**
`config = {'gmsh_path': /home/gary/gmsh-2.11.0-Linux/bin/gmsh}`

I confirmed the added PYTHONPATH as below:
```
$PYTHONPATH/
bash: ~/porepy/: Is a directory
```

However, I still get the same error when running the test.

**Comment by L4student** [comment]
Any suggestion on what I could still be doing wrong?

**Comment by keileg** [comment]
1. Verify that porepy is properly installed:
- cd /tmp (or somewhere else not in PYTHONPATH), open python, and import porpy
2. Verify that you can import porepy_config
3. Verify that the gmsh path that you have given actually points to gmsh. I would guess something like os.system(string_from_porepy_config') could help you here, but I'm not sure.

My guess is that one of these items will fail. Note that the steps that I outline probably should be modified somewhat in order to test what you want.

**Comment by L4student** [comment]
Thanks. I was able to get rid of that error, which I think was most probably coming because the gmsh path was defined without `''` in the dictionary variable in `porepy_config.py`.  
Although the previous error is gone, this time I get another error while testing as shown below:

```
test/unit/test_dual_vem.py:416: AssertionError
============================ pytest-warning summary ============================
WC2 /home/gary/porepy/test/unit/test_doctests.py cannot collect 'test_suite' because it is not a function.
========== 1 failed, 403 passed, 1 pytest-warnings in 205.45 seconds ===========
```

**Comment by keileg** [comment]
Good to hear that it works now.

The second issue you mention is known, see #49. We're working on resolving it, actually it might be that #60 (merged into develop today), but we are also fairly confident it does not impact the accuracy of the code - it looks more like something peculiar with the test. If you want to stay on the safe side, you can avoid using virtual elements for anisotropic permeabilities for now.

**Comment by L4student** [comment]
Ok. Thanks for the help.
