### ISSUE TITLE
The replace_grids method from the GridBucket class should preserve the node ordering of the graph

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy#629]
_This issue is rather technical, and you probably won't be affected if you never tried to replace grids_

The method `gb.replace_grids(g_map: Dict)` should preserve the grid ordering from the _old_ grid bucket in the _new_ grid bucket. Currently, this will only occur if _all_ nodes from the graph are replaced. However, if only _some_ nodes are replaced, the node ordering of the graph is lost. This does not qualify as a BUG, since the grids are replaced correctly,  but it might be extremely counterintuitive, in addition, of course, to being computationally expensive if this process has to be performed many times.

I will try to fix this in the future.

**Comment by keileg** [comment]
@jhabriel: Let us know before you start working on this (won't happen in the near future, I suppose). Ordering of subdomains has become a recurring issue, including when composing lists of subdomains in Ad where consistent ordering of the list items is critical, so we may want to take a broader view on this issue.

**Comment by jhabriel** [comment]
Perfect. I will let you know.

**Comment by keileg** [comment]
This will be included as part of the upcoming model rewrite.
