### ISSUE TITLE
Inconsistent sign convention for discretization/BC matrices

### ISSUE THREAD

**Issue by jwboth** [pmgbergen/porepy#630]
Discretizations of diffusive fluxes (flow/Darcy type) and advective fluxes (transport type) use different sign conventions regarding contributions of boundary conditions. While boundary condition terms are added for the former, they have to be subtracted for the latter in order to discretize/reconstruct a flux.

For instance, using a flow discretization `flow = pp.ad.TpfaAd`, a Darcy flux would be discretized by `flow.flux * p + flow.bound_flux * bc_val`, whereas given a transport discretization `transport = pp.ad.UpwindAd`, the advective flux would be discretized by `flux * (transport.upwind * c) - transport.bound_transport_dir * (flux * bc_val) - transport.bound_transport_neu * bc_val`.

**Comment by keileg** [comment]
I believe the `bound_transport_dir` and `_neu` matrices can be deleted / should not be used, but we will have to check this.
