### ISSUE TITLE
Move polyhedron file

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#632]
The external file robust_point_in_polyhedron should, according to @keileg, be fetched to the root directory rather than src. Moreover, we should add it to gitignore.

**Comment by keileg** [comment]
I forgot the exact explanation, but there are some very specific reasons why one should not put files directly in src; it has to do with making sure tests run on the version of the code one expects. I never understood if this was actually relevant with the seup we have in PorePy, but the type of bugs one risk introducing was rather deep, so better safe than sorry.
