### ISSUE TITLE
Robust Point in polyhedron Installation

### ISSUE THREAD

**Issue by RuSmith96** [pmgbergen/porepy#648]
Hi there, 
I am new to using your software Porepy (on windows) and very interested in it. 
I have ran into an issue on the tutorial of meshing fractures ->
```
ModuleNotFoundError: No module named 'robust_point_in_polyhedron'
```
Reading into this I see that I am required to install a separate module from elsewhere. But I am running into issues with this. Would you be able to explain how I can get this to work? 
Any help is much appreciated. Thanks in advance!
Cheers!

**Comment by keileg** [comment]
The important part is to run the command `python fetch_content.py`, whihc will download the extra file. There might have been a problem that the file was downloaded to a non-optimal folder, but if you pull the latest version of PorePy (after we merged #649) the file will be downloaded to the top directory of your PorePy installation, and you can run it from there. Hopefully this will take care of things.
