### ISSUE TITLE
Previous values of operators

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#655]
Is there a way to obtain previous values of operators? If not, could we accomodate the following?
```
import porepy as pp
model = pp.IncompressibleFlow({})
model.prepare_simulation()
flow_ad = pp.ad.MpfaAd(model.parameter_key, model.grid_list)
op = flow_ad.flux * model._ad.pressure
model._ad.pressure.previous_iteration()
op.previous_iteration()
```

**Comment by keileg** [comment]
My idea here has been what you sketch out in the last line: Force an operator to have all its components evaluated at the previous iteration (but not those already define at the previous time step). If implemented correctly, this could go a long way towards allowing for evaluation of Ad operators using only the residual, which will save a lot of time for linear problems; I think both @jwboth  and @OmarDuran have thought about this too.

I added this to the update Ad project; let's get back to it.

**Comment by keileg** [comment]
This will be implemented while revisiting the models.
