### ISSUE TITLE
[OLD] Unified geometry definition

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#660]
We want a unified way of defining and meshing a mixed-dimensional geometry based on
- list of fractures
- domains
- meshing
- mesh parameters
- make adding of fractures dynamic (methods with different signatures for different types of fractures)
- (optional) wrapper/extension of fracture network functionality
- (optional) local mesh size control
This could take the form of a wrapper function around existing functions (whose signatures unhelpfully depend on dimension and mesh type). Alternatively, we improve the FractureNetwork classes with unified initialisation and a simple meshing method. The latter may require more work, but is more flexible and could prove useful in instances when the geometry needs to be updated.

**Comment by OmarDuran** [comment]
Structured and unstructured mesh types should be considered.
