### ISSUE TITLE
Testing of model parameters

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy#685]
Model parameters (both default and non-default ones) should be thoroughly tested. An initial attempt to create such tests was started in [d604379](https://github.com/pmgbergen/porepy/pull/683/commits/d60437974d7e7053c6389645d4533a28f384cdc8). However, it was decided to tackle this task in a separately PR following https://github.com/pmgbergen/porepy/pull/683#discussion_r935234307 and https://github.com/pmgbergen/porepy/pull/683#discussion_r935256121.

**Comment by keileg** [comment]
Shoud be covered in the upcoming model update.

**Comment by keileg** [comment]
@jhabriel  @IvarStefansson : I think we can close this, while noting that this requires a continuous effort. Do you agree?

**Comment by jhabriel** [comment]
@keileg, @IvarStefansson: Can we close this issue?
