### ISSUE TITLE
update exporter

### ISSUE THREAD

**Issue by alessiofumagalli** [pmgbergen/porepy#69]
I'll submit an update of the exporter soon.
The idea is to introduce a class structure and for grids which are not changing in time store them (compressed as suggested in https://stackoverflow.com/questions/19500530/compress-python-object-in-memory) as vtk grid object. This is an option and time dependent grid will be handled as well. For big mesh the compromise between create the vtk grid each time step or store it need a future investigation.

**Comment by keileg** [comment]
Sounds good. I made a commit a few days ago which seems to save at least 70% of export time, but that still leaves a substantial consumption.  I have another idea that may improve further, but it should be compatible with yours.

**Comment by alessiofumagalli** [comment]
apparently the vtk objects are not pickle, anyway I'll submit soon the branch. Please test it with your code and suggest some modifications.

**Comment by keileg** [comment]
We can of course also create an export object of some form, and then store
the gVTK inside there. That will require some more memory, but should save
us from creating the object more than once.

man. 13. nov. 2017 kl. 09:41 skrev Alessio Fumagalli <
notifications@github.com>:

**Comment by alessiofumagalli** [comment]
yes, that's my strategy now. in future we can save the raw object on file and reconstruct the vtk file. or maybe choose another strategy

**Comment by keileg** [comment]
When you're ready, can you push the branch to github? I will try to speed up the point sorting using numba - that could potentially have a huge impact.

**Comment by alessiofumagalli** [comment]
yep, just figure out the last thing and then the branch is ready

**Comment by keileg** [comment]
Fixed by #70
