### ISSUE TITLE
Failing unit test from test_interpolation_tables.py

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy#711]
Build Test caught the following error when running scheduled tests:

FAILED tests/unit/test_interpolation_tables.py::test_interpolation[_QuadraticFunc-4]

This most likely indicates an issue when randomly generated values are used in the test.

**Comment by keileg** [comment]
I'm working on the tables anyhow, so I'll see if I find anything.

**Comment by keileg** [comment]
Note to self: The error is only in python 3.10 - it may be triggered by the random numbers generated.

**Comment by jhabriel** [comment]
@keileg: I think the problem is python version-independent. If you check the build from three days ago, it failed on 3.8.

**Comment by keileg** [comment]
You're right. O joy!

**Comment by IvarStefansson** [comment]
Can this one be closed?

**Comment by keileg** [comment]
Not really. I'm trying to cover it in relation to an overhaul of the interpolation tables, it will be closed in connection with that PR.
