### ISSUE TITLE
Unify ad_variable methods in models

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#717]
Inconsistent naming - we have both create_ad_variables and assign_ad_variables. Unification needed, please comment if you have preferences or stay forever silent @keileg, @jhabriel, @OmarDuran and @jwboth.

**Comment by jhabriel** [comment]
After checking the current usage, my vote goes for `create_ad_variables`.

**Comment by OmarDuran** [comment]
My vote is for `create_ad_variables`.

**Comment by jwboth** [comment]
I think there exists reasons for both. Yet, at the moment, `create_ad_variables` seems also the close winner for me. But I can live with both.

**Comment by keileg** [comment]
Fine with me.
