### ISSUE TITLE
Invalid Colon character in examples/papers/ArXiv for Windows

### ISSUE THREAD

**Issue by mstarnoni** [pmgbergen/porepy#72]
I was trying to clone the project on Windows and got this invalid argument error.
@alessiofumagalli can you please change names to folders and replace ':' perhaps with '_'?

**Comment by mstarnoni** [comment]
Update: installation from source via 'git clone https://github.com/pmgbergen/porepy.git' still throws the error: 'fatal cannot create directory at 'examples/papers/ArXiv:1610.02905': invalid argument'.
So I downloaded the zip porepy-develop, this time the folder is changed correctly in 'examples/papers/ArXiv_1610.02905'.  
Now I run 'conda install --yes --file requirements.txt' and get the error:
'CondaValueError: Malformed version string '2016.2;platform_system=="Linux"': invalid character(s)

**Comment by alessiofumagalli** [comment]
I see your point, never thought that Windows has different name conventions. For me your change is acceptable, the meaning is still kept. About the second problem you have I don't really have any experience.

**Comment by keileg** [comment]
Looks like the setup script has not been tested too much on windows either.
It may be that it should be ', or whatever Windows use to denote
apostrophes. You can also just remove the line - as you see, the package
will not be installed anyhow.



tir. 14. nov. 2017 kl. 12:05 skrev Alessio Fumagalli <
notifications@github.com>:

**Comment by mstarnoni** [comment]
Update.
Two packages still don't work. I get PackageNotFoundError for meshio while apparently enum is not compatible with Python 3.7 (which is the version I have installed).

**Comment by keileg** [comment]
enum34 is no longer necessary. Removed from requirement list by #74 .

**Comment by mstarnoni** [comment]
Right, I am now running the basic Get started tutorial and get the error:
from porepy.params import tensor
ImportError: cannot import name 'tensor'

**Comment by keileg** [comment]
With that error, I would guess no imports work. Are you sure you have
installed porepy in your current environment? Try pip freeze, and look for
porepy in the list.

**Comment by mstarnoni** [comment]
Yes there is porepy==0.0.9

**Comment by mstarnoni** [comment]
Right, porepy works fine with this script

import numpy as np
import scipy.sparse as sps

from porepy.grids import structured
from porepy.viz import plot_grid
#from porepy.params import tensor
#from porepy.params.data import Parameters
from porepy.params.bc import BoundaryCondition

Nx = Ny = 10                                         
g = structured.CartGrid([Nx, Ny], [1, 1])
g.compute_geometry()

plot_grid.plot_grid(g, info="all", alpha=0, figsize=(15, 12))

the two commented lines give the following problems:
-ImportError: cannot import name 'tensor'
-ModuleNotFoundError: no module named 'porepy.params.data'

**Comment by mstarnoni** [comment]
SORTED
I found out I had not installed the most current version (due to that invalid colon argument).
So for example in the \params folder I did not have the file 'tensor' but instead two files ' second_order_tensor' and 'fourth_order_tensor'.

**Comment by keileg** [comment]
Can we close this one?

ons. 15. nov. 2017 kl. 14:04 skrev mstarnoni <notifications@github.com>:

**Comment by mstarnoni** [comment]
I believe so
