### ISSUE TITLE
impossible to install gmsh and porepy in MacOS

### ISSUE THREAD

**Issue by Francyrad** [pmgbergen/porepy#726]
Hello, i'm new to the program.

I succesfully installed all the dependencies, except to nmsh.
When i try to pip install .     , the terminal says:

francyrad@MacBook-Pro-di-Francesco porepy % pip3 install .
Processing /Users/francyrad/Downloads/porepy
  Preparing metadata (setup.py) ... done
Requirement already satisfied: future in /opt/homebrew/lib/python3.10/site-packages (from porepy==1.6.0) (0.18.2)
ERROR: Could not find a version that satisfies the requirement gmsh (from porepy) (from versions: none)
ERROR: No matching distribution found for gmsh

i tried to pip install gmsh, i got the same error. I tried to install it also via pkg and via source code. i did it, i also tried to set an environmental variable. However i could not successfully do the pip install. What should i do to solve the problem? The help page of gmsh didn't help

**Comment by alessiofumagalli** [comment]
Dear Francesco, which version of python are you using?

**Comment by Francyrad** [comment]
I'm using version Python 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin

**Comment by OmarDuran** [comment]
Dear Francesco, your issue appears to be related to the installation of `gmsh` and not directly to PorePy. In order to install PorePy,  you want to make sure the command `pip install -r requirements.txt` successfully installs all the dependencies in your environment. After that, `pip install .` should work.

**Comment by Francyrad** [comment]
Dear users
Yes, the issue is related to gmsh. All the other dependencies have been installed successfully. The point is that pip install -r requirements.txt doesn't work because it tries to install gmsh. It says:

francyrad@MacBook-Pro-di-Francesco porepy % pip3 install -r requirements.txt
Requirement already satisfied: future in /opt/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.18.2)
ERROR: Could not find a version that satisfies the requirement gmsh (from versions: none)
ERROR: No matching distribution found for gmsh

So the problem is due to install gmsh in macos, which is actually impossible. Consequentially, it's impossible to install porepy in macos. I asked here because i couldn't find any solution to the web and because, maybe, some of the users already faced this problem and you know how to solve it.

I already installed gmsh via source code and via pkg, however it's like porepy cannot find it. Do you know what would i write as a path? I already tried and it's like invisible.

hope for a harmonious solution

**Comment by OmarDuran** [comment]
Dear Francesco, may I ask you to try on this command:
`pip3 install -i https://gmsh.info/python-packages --force-reinstall --no-cache-dir gmsh`

**Comment by Francyrad** [comment]
Dear Omar. I tried and it says me this:

francyrad@MacBook-Pro-di-Francesco porepy % pip3 install -i https://gmsh.info/python-packages --force-reinstall --no-cache-dir gmsh
Looking in indexes: https://gmsh.info/python-packages
ERROR: Could not find a version that satisfies the requirement gmsh (from versions: none)
ERROR: No matching distribution found for gmsh
WARNING: There was an error checking the latest version of pip.

pip3 is upgraded:

francyrad@MacBook-Pro-di-Francesco porepy % pip3 install --upgrade pip
Requirement already satisfied: pip in /opt/homebrew/lib/python3.10/site-packages (22.2.2)

**Comment by keileg** [comment]
This sounds like a gmsh-related question, so I think you will be better off asking the question in a gmsh-related forum.

**Comment by Francyrad** [comment]
Dear users, as suggested, i asked in the gitlab forum of gmsh and i solved in this way:

pip install -i https://gmsh.info/python-packages-dev --force-reinstall --no-cache-dir gmsh

for m1 chips actually only works the development versions. In the future they will fix this. Thank you anyway!

**Comment by keileg** [comment]
Thanks for sharing this.
