### ISSUE TITLE
Negative times and variable parameters in `TimeManager`

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy#734]
**Allowing for negative time**
Motivation: In some simulations it is useful to use negative times (say, to achieve some equilibration and only starting the _active_ part of the simulation) afterwards. 
Implementation: The only thing that we have to be sure here is that the sanity checks are in place.

**Variable time parameters**
Motivation: When different time scales are present in a simulation, we might need to use different parameters (e.g., `dt_min_max` or `iter_relax_factors`) for the different time scales.
Implementation: Assume that the different time scales are specified as part of the `schedule`. Then, the implementation will require a given `parameter` to be specified as a list of length `schedule.size - 1`. To give a concrete example: for `schedule = [0, pp.SECOND, pp.HOUR, pp.YEAR]`, we might be interested in prescribing `dt_min_max = [(0.001, 0.1), (0.001 * pp.HOUR, 0.1 * pp.HOUR), (0.001 * pp.YEAR, 0.1 * YEAR) ]`. Good unit tests must be written to guarantee that this actually works.

**Comment by keileg** [comment]
@IvarStefansson @jwboth do you think we can close this?

**Comment by IvarStefansson** [comment]
Yes. We'll tackle related issues if and when they arise.
