### ISSUE TITLE
Partial integration of TimeSteppingControl into models

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy#735]
Integrate the time-stepping class into the models in a non-invasive way. Meaning, that this will be only a partial integration, where all the models will behave exactly the same, but the time control will now be managed by the `tsc` object. 

The integration will aim at modularising the TSC class as much as possible. Therefore, the temporal attributes will be purged from all time-dependent models. A time-dependent model will  be in communication with the `tsc` object (i.e., to access the current time step) only via `run_time_dependent_model()`. 

Milestones:
- [x] Make `iterations` an optional parameter, since it is not really needed for linear systems or constant dt -> Unit tests.
- [x] Raise warning when `iterations` is given and `recompute_solution=True` -> Unit tests.
- [x] Add `time_index` as a public attribute of `tsc` object.
- [x] Add methods to increase time and time index -> Unit tests.
- [x] Purge time-dependent attributes from `SlightlyCompressibleFlow` and `ContactMechanicsBiot` model classes.
- [x] Integrate `tsc` into `run_time_dependent_model()` -> Integration tests
- [x] Update documentation of affected classes

**Comment by IvarStefansson** [comment]
For now, information related to non-linear iterations (counters) will remain in the models, right?

**Comment by jhabriel** [comment]
Yes. This will be most likely the next step.
