### ISSUE TITLE
BUG: Compatibility check between scheduled and simulated times

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy#736]
When comparing simulated and scheduled times, due to floating point arithmetic, sanity checks fail when they are supposed to pass.

We need to improve the sanity check by introducing some type of tolerance and update the unit tests accordingly.

**Comment by IvarStefansson** [comment]
Yes, something like np.all(np.isclose(test_values, known_values)) is much more robust than test_values == known_values

**Comment by jhabriel** [comment]
Indeed. I'm working on it.
