### ISSUE TITLE
Add possibility to export scheduled times

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy#740]
Once the `TimeManager` is fully integrated into the models, we should provide the following exporting options:

1. no time
2. every time
3. scheduled times

This could be implemented, for example, inside `after_netwon_convergence()` as a method, say:
`export_solution(times_to_export: Literal[none, all, scheduled] = none)`,
where `none` refers to no time, `all` refers to all times, and `scheduled` to scheduled times.

The default behaviour is to export no time.

**Comment by IvarStefansson** [comment]
I think the definition of when to export should be in the parameter dictionary rather than the signature of the method

**Comment by jhabriel** [comment]
Yes, that would be better.

Something like:

times_to_export = self.params.get("times_to_export", "none")
export_times(times_to_export)
