### ISSUE TITLE
Abstract time control class

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy#751]
After integrating the `TimeManager` class into the models, it is evident that time control in general will benefit from (at least some level of) abstraction.

One could think of creating an abstract class, e.g., `AbstractTimeControl` from which specific time management strategies will inherit. 

For example, the current `TimeManager` can then be split into two classes, i.e., `ConstantTimeStep` and `IterationBasedTimeControl`. This will save us from many `if` statements that are currently in place to deal with constant time step. In addition, it will unlock the possibility to implement other types of time management strategies, such as `ResidualBasedTimeControl`.

**Comment by jhabriel** [comment]
The abstract class should contain only minimally required attributes such as `schedule` and `dt_init`, and methods to march increase `time` and `time_index`.

**Comment by IvarStefansson** [comment]
Good observation. I envision TimeManagers as one component of a modularised SolutionStrategy class.

**Comment by jhabriel** [comment]
Yes, I think that's the direction we should head to. I will try to sketch something after #752 is merged.

**Comment by IvarStefansson** [comment]
I would not prioritize this until the model_refactoring branch is more mature/merged

**Comment by jhabriel** [comment]
I will close this issue since we have decided in person that this will not be a strategy that we want to pursue.
