### ISSUE TITLE
Upwind discretization produces wrong results in case of outflow/inflow boundaries

### ISSUE THREAD

**Issue by vlipovac** [pmgbergen/porepy#760]
I realized in one of my simulations that the Upwind class does not process fluxes on boundary faces properly, which have a non-zero outflux/influx.

- ``Upwind.upwind``: Gives a upwind map from cells to internal faces and **nulls fluxes on boundary faces**
- ``Upwind.bound_transport_dir``: Gives a map from set Dirichlet BC for weights defined on the Dirichlet boundary (to be used in combination with a flux array with values per face)
- ``Upwind.bound_transport_neu``: Gives a map to include defined Neumann BC for the "whole flux", including weight.

Above excludes boundaries, where there is an outflux/influx and no BC where set for the upwinded weight.

**Example:**
 ``div(a grad(p))``
 where ``grad(p)`` represents a flux
 ``Upwind.bound_transport_dir`` covers the case when Dirichlet BC were set for ``a``
``Upwind.bound_transport_neu`` covers the case when Neumann BC were set for the whole expression ``a grad(p)``

But assuming a part of the boundary ``G``, on which any BC were set for ``p`` leading to an out/influx, above three discretizations do not provide a proper upwinding for ``a``, resulting in sort of accumulation, as can be seen in a simple[ linear tracer model implemented here:](https://github.com/pmgbergen/porepy/blob/composite_flow_extension/testmodel.py)

_Channel flow with constant D-BC for pressure on left and right and D-BC for Upwind class on the left side._
_Here the missing functionality of the Upwinding class leads to an accumulation at the outflow boundary on the right side._

![tracer_accum](https://user-images.githubusercontent.com/68282540/200348594-ee3b0851-6758-489f-a129-d2b3e4f8d39b.jpg)

**Comment by vlipovac** [comment]
I have pushed a temporary fix as a starting point for the discussion @keileg @OmarDuran 
Let me know what you think
Here is the proposal:
https://github.com/pmgbergen/porepy/compare/develop...upwind-issue-760

**Comment by IvarStefansson** [comment]
I've had a look and discussed with Veljko. We have a plan on how to do a more permanent fix.

**Comment by OmarDuran** [comment]
I think we should aim to purge the "dir" and "Neumann" bc matrices and treat the boundaries with a more general boundary object that supports the case of switching between inflow and outflow boundaries.

**Comment by OmarDuran** [comment]
As a separate comment, we should create a PR to solve both https://github.com/pmgbergen/porepy/issues/760 and  https://github.com/pmgbergen/porepy/issues/630

**Comment by keileg** [comment]
I agree that we should do away with the Neumann-Dirichlet difference if possible. 

As for the Ad compatibility, upwinding is defined according to the flux field from the previous iteration, so it must be computed, either by `compute_darcy_flux` or perhaps by a similar method in the new models (I'm guessing here). The Heaviside function in the formulation means it should not be differentiated, for that we need hybrid upstreaming, but that's another story.

Note that it is only the direction of the flux which is taken at the previous iteration, the flux magnitude can already be treated fully implicitly by Ad.

**Comment by OmarDuran** [comment]
It was misleading to use the term ad compatible. So I didn't mean full differentiation on the conditionals or on the image of a piecewise function. In my suggestion, what I meant by ad-compatible is to somehow encapsulate the delayed evaluation of flux signs somewhere. For example in the wrapper pp.ad.UpwindAd such that calling of pp.fvutils.compute_darcy_flux and discretize are performed seamlessly.

**Comment by keileg** [comment]
Agree, that would be useful; it is much the same as updating solution-dependent permeabilities. This should be handled on the level of the Ad-machinery, though. I have some thoughts, but I think we should wait until after the model refactoring is done.

**Comment by IvarStefansson** [comment]
The first step, evaluating Darcy fluxes "directly" from AD and not calling compute_darcy_flux, is already implemented in model_refactoring

**Comment by vlipovac** [comment]
As discussed with Omar, the Upwind class seems to bypass the issue (or let me rather say its intended use) by using the same BoundaryCondition object which is used for the flux discretization. I.e. flagging the outflow boundary as Dirichlet, like for the flux.

I will therefore close this issue.
The lack in documentation and tutorial remains.
