### ISSUE TITLE
issue in requirements

### ISSUE THREAD

**Issue by rbe051** [pmgbergen/porepy#77]
I just did a clean install of porepy and conda, but got a issue when trying to install the requirements in pip.

I did:
conda create --name porepy python=3.6
source activate porepy
pip install -r requirements-dev.txt

However, something broke in the downloading of pymetis:
    ModuleNotFoundError: No module named 'six'

I installed six with pip, and after that everything ran smoothly

**Comment by keileg** [comment]
This sounds vaguely familiar. It might be that six is an implicit requirement of some other package we're using. It may also be that this is Windows specific - I think I saw something similar there many months ago.

I've added six to the requirements, dab7597. Will merge once the tests have passed.
