### ISSUE TITLE
Update requirements to include Sphinx

### ISSUE THREAD

**Issue by vlipovac** [pmgbergen/porepy#774]
For PorePy docs to be buildable using Sphinx, two packages are required

- sphinx
- sphinx-rtd-theme

The first one includes the builder and apidoc.
The second one the standard readthedocs theme template.
Developers only.

**Comment by OmarDuran** [comment]
Is this issue related to a specific GitHub action or another automated process?

**Comment by vlipovac** [comment]
As discussed internally, requirements for the docs will be handled separately.
