### ISSUE TITLE
Rework documentation: grids

### ISSUE THREAD

**Issue by vlipovac** [pmgbergen/porepy#778]
Reworking the sub-package ``porepy.grids`` in terms of new docstring & typing conventions.

Working branch https://github.com/pmgbergen/porepy/tree/docs_update_grids

Files to be reworked

1. __init__ status: **reviewed**
2. coarsening status: **reviewed**
3. grid_extrusion status: **reviewed**
4. grid status: **reviewed**
5. match_grid status: **reviewed**
6. md_grid status: **reviewed**
7. mortar_grid status: **reviewed**
8. partition status: **reviewed**
9. point_grid status: **reviewed**
10. refinement status: **reviewed**
11. simplex status: **reviewed**
12. structured: status: **reviewed**

**Comment by Yuriyzabegaev** [comment]
I take 4 - grid

**Comment by mariusnevland** [comment]
I will take md_grid

**Comment by vlipovac** [comment]
I'll cover:

1. init
2. coarsening
3. grid_extrusion
12. structured

**Comment by IngridKJ** [comment]
I'll cover:
1. point_grid
2. partition
3. refinement

**Comment by Yuriyzabegaev** [comment]
My three files are ready for review.

**Comment by mariusnevland** [comment]
My files are ready for review.

**Comment by IngridKJ** [comment]
My files are also ready for review.

**Comment by vlipovac** [comment]
@IngridKJ @Yuriyzabegaev @mariusnevland 

I have reviewed your files and made several changes, some of which are due to changes in the style guid.

In general, good work, thank you! 

I have only a small remark:
Including cross-referencing and proper in-line formatting is sometimes cumbersome, but this contributes highly to the readability and to people being able to navigate quickly through the docs and to other. Don't hesitate to use them.

I am sending this now as a PR and we will see what the other say. Keep yourself up-to-date in case someone suggests changes to any of your files.
