### ISSUE TITLE
Update tutorials

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#79]
The branch extended_testing contains a script test/regression/check_tutorials.py that runs all tutorials (e.g. all *.ipynb in the tutorials folder) and leaves an assertion error if something goes wrong. And something indeed goes wrong. 

@alessiofumagalli @rbe051 @IvarStefansson Please check that 'your' tutorials are working, or make them work. When this is done, and I've fixed mine I will try to add this job to the daily run.

**Comment by alessiofumagalli** [comment]
I do single-phase flow now

**Comment by alessiofumagalli** [comment]
do we need to add consistency check? is it still based on assertion on the solution?

**Comment by keileg** [comment]
You can add it if you want, and if it is natural. If so, make sure to
comment why this is included in the notebook.

ons. 22. nov. 2017 kl. 09:35 skrev Alessio Fumagalli <
notifications@github.com>:

**Comment by alessiofumagalli** [comment]
single-phase flow tutorial updated with consistency checks

**Comment by rbe051** [comment]
Commit: 1bb68e551be8a8cbb28bc3917a6f2dbaceac0d4f updates my tutorials. Sorry it took some time

**Comment by keileg** [comment]
Commit 22f33c17 will hopefully trigger a test script for tutorials during cron runs. I will not be surprised if this takes some trials to get right though.

**Comment by keileg** [comment]
I believe we are there now. The next task is then to create more tutorials, our coverage should be better.

**Comment by keileg** [comment]
The status is reasonably good here, so I'm closing.

Next effort is to create more tutorials.
