### ISSUE TITLE
Rework docstrings in subpackage fracs

### ISSUE THREAD

**Issue by vlipovac** [pmgbergen/porepy#794]
## Activity coordination

The active issue pmgbergen/porepy#780 is currently being processed by @jhabriel and his workgroup.

Affected files are:

- `fracture.py`
- `fracture_importer.py`
- `fracture_network_2d.py`
- `fracture_network_3d.py`
- `line_fracture.py`
- `plane_fracture.py`

The docstring-rework in above files will be included in the refactoring.

Remaining files in the subpackage `fracs` are to be updated to latest PorePy style by @vlipovac .

## Remarks

- The splitting between private and public members needs to be reiterated.
- Special care in the rework must be given to the `gmsh` interface.
- Other subpackages like `numerics.fracture_deformation` are using `fracs` extensively. Changes in typing and/or private-public-status of members must be refactored with care.

**Comment by jhabriel** [comment]
Closed after #866
