### ISSUE TITLE
more examples of using your package

### ISSUE THREAD

**Issue by trimonova** [pmgbergen/porepy#811]
Thank you very much for creating your package. Do you have more examples of using your package somewhere.
We have a simple task ahead of us. Obtain pore pressure in an area with permeability differing in points. In the center is a well with a constant flow rate. The task is non-stationary.
Unfortunately, the information from the tutorial from the git hub is not enough for me.
Next, we plan to replace the permeability distribution with a fracture distribution.

Best regards, Mariia Trimonova

**Comment by keileg** [comment]
As communicated through other channels, but repeated here for completeness, all information and examples which is in a reasonable shape, is available in the tutorials. We are actually working on expanding these, but for capacity reasons, we cannot promise anything in terms of how frequent and thorough these updates will be.

**Comment by keileg** [comment]
I will close this now, feel free to reopen.
