### ISSUE TITLE
Duplicated functionality for error computation

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#826]
We have some duplicated functionality related to error computation. 

Relevant code:
- [verification_utils](https://github.com/pmgbergen/porepy/blob/develop/src/porepy/applications/building_blocks/verification_utils.py)
- [error](https://github.com/pmgbergen/porepy/blob/develop/src/porepy/utils/error.py)

My hunch is that we'd like to purge some duplication and possibly restructure the remaining functionality. We should consider file/method names critically to make sure users can find this code.

**Comment by IvarStefansson** [comment]
@jhabriel, do you agree that this could be a good user group project? Would you like to be involved in the capacity of Mr. Verification?

**Comment by jhabriel** [comment]
Yes. This will make an interesting short user project.

I would like to be involved, yes.
