### ISSUE TITLE
Default parameter values

### ISSUE THREAD

**Issue by IvarStefansson** [pmgbergen/porepy#847]
Porepy contains classes with values for some rock and fluid types. These should be removed in favour of an approach compatible with MaterialConstants classes. The current idea is to provide for each material a dict[str: float] somewhere in applications. This facilitates usage s.a.
```
fluid_vals = pp.material_constant_values.water
fluid_vals.update(my_vals_as_dict)
fluid = pp.FluidConstants(fluid_vals)
```

**Comment by saeunnh** [comment]
To my knowledge this is the best openly available database of rock properties. It provides a list of rock samples taken, location, properties measured and reference. 
https://essd.copernicus.org/articles/12/2485/2020/
