### ISSUE TITLE
Negative defined mechanics submatrix

### ISSUE THREAD

**Issue by Yuriyzabegaev** [pmgbergen/porepy#849]
Hei,

I noticed that the matrix arising from the mechanics problem in PorePy is negatively defined. It has a dominant negative diagonal and gives a negative scalar when multiplied by a random vector from left and right. That's alright if we solve the mechanics block separately, but it might lead to suboptimal solver performance if we couple mechanics with something else. For example, the single-phase flow problem matrix is positively defined.

Providing the code to reproduce:

```
import matplotlib.pyplot as plt
import porepy as pp

model = pp.poromechanics.Poromechanics()
pp.run_stationary_model(model, {})
mat, rhs = model.linear_system
plt.matshow(mat.A)
plt.colorbar()
```
Result:
![image](https://user-images.githubusercontent.com/24578236/229542745-a555044f-b1b4-4330-9820-9050fcd0e87f.png)

**Comment by Yuriyzabegaev** [comment]
@jhabriel yes the result is the same.

**Comment by Yuriyzabegaev** [comment]
@IvarStefansson if we test the incompressible single-phase flow setup (elliptic problem), the diagonal values remain positive. As you suggested, it must be a scalar and vector divergence inconsistency.

**Comment by IvarStefansson** [comment]
Thanks for checking!
@keileg, could it be that the sign convention is different between mpfa.flux and mpsa.stress?
