### ISSUE TITLE
Some questions about THM

### ISSUE THREAD

**Issue by zgl188** [pmgbergen/porepy#850]
Hello!
I am a student from China University of Mining and Technology Bei Jing (CUMTB), I am using porepy to study about THM, but when I run the example of the essay "Numerical Modelling of Convection‑Driven Cooling, Deformation and Fracturing of Thermo‑Poroelastic Media", it always tells me wrong, and I find it used porepy 1.3.0, but I use docker to get the image of porepy, docker just give me porepy 1.6.0, so could you tell me how to get the docker image of porepy 1.3.0 to run the example? Because I don't know how to write my example of THM, I want to learn from the example of the essay.

**Comment by IvarStefansson** [comment]
Hello! 
Unfortunately, we do not provide Docker images of earlier versions of PorePy. If you want to run the example simulations for the paper, you'll have to install PorePy from the GitHub source checking out the commit specified in the publication. Please also refer to the [installation instructions](https://github.com/pmgbergen/porepy/blob/develop/Install.md).

**Comment by zgl188** [comment]
Thanks for your answer!
But I don't know how to run the simulations of hydrofracturing the hot dry rock after I have read the tutorials, could you teach me how to write a simple example for simulating the THM please?

**Comment by IvarStefansson** [comment]
The fracture propagation code is not in current use. I'm afraid the only documentation we provide on it is in the paper you mentioned and as code documentation in the relevant Python files.

**Comment by zgl188** [comment]
Thanks for your answer!
And I want to know that could I use the porepy on the win10?  When I pip install porepy, it tells can't find it, so if it can, how can i achieve it ?

**Comment by IvarStefansson** [comment]
You can use PorePy on Windows 10, yes. We are not able to provide assistance on issues with installing related to your local setup. You'll have to fix these on your own.

**Comment by keileg** [comment]
I will close this one now.
