### ISSUE TITLE
Porepy Installation

### ISSUE THREAD

**Issue by DorAxel023** [pmgbergen/porepy#857]
Hello,

I have been struggling with installing PorePy.

I have the following error as shown in the image below:
![image (1) (1)](https://user-images.githubusercontent.com/130547593/231646234-791378f4-63c4-4e2b-86a2-3020be4cc1f0.png)

Please, how can I solve this error?

Looking forward to hearing from you.

Thank You !!

**Comment by DorAxel023** [comment]
Hello, please can someone help me to solve my request?

Best Regards,
Axel

**Comment by jhabriel** [comment]
Hi Axel,

From the first cell of your notebook (the one mark with [26]), it seems that PorePy is correctly imported. Without further information about what you are trying to solve or which script you are running, my best guess is that you are using an outdated version of PorePy, one that does no longer supports the `Ad_array` class.

I would recommend to either update your script to run with newest version of PorePy (the one from the develop branch), or alternatively, to use an older version that works on your script.

Hope this helps.

**Comment by DorAxel023** [comment]
Dear Jhabriel,

Thanks for your answer.
Please where can I find the Porepy version from the develop branch? 


Thhank You.

**Comment by jhabriel** [comment]
Hi Axel, 

The develop branch is the default branch, e.g., https://github.com/pmgbergen/porepy/tree/develop. This is the branch that will contain the latest changes.

Best Regards.

**Comment by DorAxel023** [comment]
Thank You !!!
