### ISSUE TITLE
Unclear operator evaluation from iteration and time step index

### ISSUE THREAD

**Issue by vlipovac** [pmgbergen/porepy#881]
According to the docs of `Operator.evaluate`, it will pull values from the previous iterate, alternatively from the  previous time step.

But when I instantiate my variable like this
![image](https://user-images.githubusercontent.com/68282540/235957599-45a7dc11-5974-4a37-8c51-05620b16224e.png)

and evaluate an algebraic combination of variables using simply `.evaluate(ad_system)`, I get the following error.
![image](https://user-images.githubusercontent.com/68282540/235958002-e25c714d-d8b7-47b2-8429-fde27d40b78e.png)

This error happens during a call to `.get_variable_values` (in line 710 of `operators.py`)
The `iterate_index` argument is None and the `time_step_index` is 1, as per call from `evaluate`

Assuming I did everything right, there seems to be either an inconsistency in the documentation or a missing implementation?
According to the docs the implementation should be able to find the values stored at iterate index 0.

If I instantiate a variable with values at both iterate and time, the error does not happen.

**Comment by keileg** [comment]
Your final statement is the key: You need to initialize the relevant arrays before they can be fetched. So this is not a bug, but arguably a tacit assumption in the `EquationManager`.

**Comment by IvarStefansson** [comment]
> Your final statement is the key: You need to initialize the relevant arrays before they can be fetched. So this is not a bug, but arguably a tacit assumption in the `EquationManager`.

Or `EquationSystem`, rather. But yes, I think it's fair that you need to set the value for the previous time step before being able to get that value.

**Comment by vlipovac** [comment]
Alright.

Then maybe the documentation should be updated, because to my understanding it says that it is optional ("alternatively").

And does that mean that time-independent problems also need a first time-index set for their variables?
It seemed intuitive to me that the iterative index is prioritized (like the previous approach took ITERATE first, than STATE)

![image](https://user-images.githubusercontent.com/68282540/236304856-29459b74-41f9-47b5-90aa-09477960fecf.png)
