### ISSUE TITLE
Unit test fails locally

### ISSUE THREAD

**Issue by mariusnevland** [pmgbergen/porepy#908]
The test dual_hybrid_vem_2d_ani_simplex fails locally on my computer. The problem seems to be a slightly too strict tolerance (10^-15). If I increase the tolerance to 10^-14, the test runs successfully.

**Comment by mariusnevland** [comment]
I am using Windows 10 with an Intel processor. All of the required packages have been installed with conda. I am using:

Numba 0.57.0
Numpy 1.24.3
Scipy 1.10.1

**Comment by IvarStefansson** [comment]
What's the status on this, @mariusnevland?

**Comment by mariusnevland** [comment]
I haven't looked more into this yet @IvarStefansson.
