### ISSUE TITLE
Use an imported permeability mesh and solve for flux?

### ISSUE THREAD

**Issue by L4student** [pmgbergen/porepy#91]
Is it possible to import two `m x n` arrays depicting permeability and porosity, respectively, and use that to solve for single-phase flow in *porepy*? I would like to solve for flux (flow rate) with given boundary conditions on a Cartesian mesh that is simply the imported array without any discrete fracture because the imported permeability (and porosity) values are implicitly accounting for the presence of fractures. Another related question - can I use the pressure at each time step to **modify** my permeability array and use that  modified permeability for the pressure/flux calculation on next time step? It would be really useful to have this capability in *porepy* if it's not there currently.

**Comment by keileg** [comment]
Yes, you would basically need to follow the tutorial on Darcy's law, although driven by boundary conditions instead of a source term.

We have not implemented dynamic updates of permeability and porosity, but you can initialize a new problem for each time step (the overhead should be minor); actually the code is being used in this way already.  It is not included in the code base though, as the constitutive law for the updates will likely vary significantly with rock types, flow scenario etc, thus it is best dealt with by the user.

**Comment by L4student** [comment]
Thanks. I saw the [Darcy_eqn](https://github.com/pmgbergen/porepy/blob/develop/tutorials/Darcy_equation.ipynb) tutorial where you are assigning permeability using the matrix or fracture domain class. I do not, however, see permeability defined for the matrix in the matrix domain class, plus I also do not see any porosity term there. Can I assign the perm/poro for only matrix  (no fractures) as done in this example for fractures?

Regarding the dynamic update of permeability and porosity, can you briefly cite the relevant command/code/example to initialize the problem as you suggest? I have not used *porepy* yet, so I am not well aware of the working of the code.

**Comment by keileg** [comment]
You would need to create a permeability function in the MatrixDomain, just as for the fracture. The problem will be set up with default parameters, unless they are overwritten, as illustrated in the tutorial. I overlooked that you mentioned porosity - I suppose that mean you solve a compressible problem. If so, the tutorial on Slightly compressible flow should be a better guide.

I don't think the permeability updates are pushed to github, they are likely only found in runscripts here and there. But to give you some hints, you would need to implement the constitutive law for the update, and then redefine the model after the permeability update. So, a rough pseudo-code would be

for each time step:
    define FractureDomain to assign the current permeability
    set up a new EllipticModel that uses the new permeability
    solve
    recompute aperture / permeability. Ready for next time step.

If you solve large problems (definition depends on mesh size among other things), the full recreation of the problem may be inefficient, but for starters it should work.

**Comment by L4student** [comment]
Hello. I am interested in gas production data (from few cells in absence of any well model) from a tight reservoir for which I have the permeability model (and porosity model). I am not interested in changing the permeability (or porosity) with time as earlier commented. Plus, I am not interested in mechanics...I am only interested in simple flow (production) data with time at this moment. Also, I am not interested in defining explicit fracture networks because my permeability (and porosity) take care of fractures implicitly. I tried looking at the '[Slightly Compressible Flow](https://github.com/pmgbergen/porepy/blob/develop/tutorials/slightly_compressible_flow.ipynb)' example, but there are few things that keep me from simulating this simple problem. For instance, I am not sure how to include a production/well node/zone, access the production results as numpy array or list, etc. I have attached a small script that is missing these features. Can you please help to run this small example as desired? I would appreciate if you could edit this file to include few production nodes in the middle (I am not injecting anything), solve and save production at each time step.

[compressible_gas_flow.zip](https://github.com/pmgbergen/porepy/files/1579784/compressible_gas_flow.zip)
