### ISSUE TITLE
Bug in fracs.split_grid()

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#92]
For certain fracture networks, an error occurs in the function duplicate_nodes(), around L480. The symptom 
is indexing with an index iv that is too long compare to the array length. 

It seems the bug was introduced in d34fff4, or one of the preceding updates.

I have not managed to recreate the error on a small network (<40 fractures 3D), let me know when you need a case.

**Comment by rbe051** [comment]
Reverted to an older version of split_grid. Let me know if this works

**Comment by keileg** [comment]
I ran into trouble in split_nodes. Apparently, I end up with a node that has no cells (the actual error message comes from __extract_submatrix which cannot handle empty matrices). Runscript for debugging to come.

**Comment by keileg** [comment]
Also, my impression is that the memory usage was quite heavy. The simulation that crashed had a peak memory (in split_fractures()) of at least 8GB for a mesh with ~250.000 fractures. I'm not sure if this is unavoidable, but it is a lot.

**Comment by rbe051** [comment]
This is related to the speed issue. The old version of split_grid we reverted to uses a lot of memory (thus is also slow), due to the slicing of the matrices. When I find the bug in the optimized split_grid, I will cut the memory need considerably.

**Comment by keileg** [comment]
I tried again, without detecting the issue. This thing feels like a ghost.

I will close this now, and reopen if trouble reappears.

**Comment by rbe051** [comment]
Do we want to merge the optimized split grid back into develop?

**Comment by keileg** [comment]
No, the bug is back again. I will keep you posted.

**Comment by keileg** [comment]
If you consider the notebook just pushed to branch flow_transport_pp, path examples/papers/arxiv171000460 , there is a create_grid function there. When I ran that function in optimize split grid, I got into trouble.

Also note you may need to use updated version of gmsh (3.06 rather than 2.11) to create grid. I will change install instructions.

**Comment by rbe051** [comment]
Everything works fine for me......

**Comment by keileg** [comment]
Interesting. I will look into it. Sigh.

**Comment by rbe051** [comment]
Are you feeling brave enough to try to merge the optimization back in? It would be nice to cut the gridding time with an order of magnitude

**Comment by keileg** [comment]
This was the strange behavior in splitting of the fractures, that only
showed up occasionally on my computer? If so, let's give it a try.

Eirik

**Comment by rbe051** [comment]
Ok, I will test the branch again on my computer, and if it works, I will merge it

**Comment by rbe051** [comment]
merged optimization back in develop in commit: 4e50bb593fd0b1a18750e82d52ac0139f52289ff
