### ISSUE TITLE
Update to networkx 2.0

### ISSUE THREAD

**Issue by keileg** [pmgbergen/porepy#97]
Networkx seems to have changed the underlying data structure when updating to 2.0. We're fixed at <2 for now, but need to move on at some point. Or write our own graph class.

**Comment by DavideBaroliUniLu** [comment]
In porepy/grids/grid_bucket.py Line 227 `self.graph.neighbors(n)` is not anymore a list but a dictionary keyiter.
You could fix it by  ` list(self.graph.neighbors(n))`.

**Comment by keileg** [comment]
Thanks.

I will likely postpone the update a little bit, and do some general
maintenance of the GridBucket at the same time. Things are working nicely
with the old version of networkx, it is just not sustainable in the long
term.

**Comment by keileg** [comment]
Update to networkx in #124; the code should now work with networkx 1.x and 2.x
